### ISSUE TITLE
Relations need more content

### ISSUE THREAD

**Issue by fulv** [plone/training#101]
It says:  `I show you how to do it TTW...`, but I have never used relations, so I have no idea how to fill in those blanks.  If you want to tell me in person on a call, @pbauer, I can add the text.

**Comment by pbauer** [comment]
@fulv You can add relations (list or choice) in the dexterity schema-editor. You can even define allowed types inthe editor. Give it a try. But I think the is a full chapter missing there... 
At some point (probably here) we add a relation-field to the talk-content type. (See how in the code there is a chapter 14_speaker_p5 and chapter 33 'relations' has no snippet on top to copy the code. @do3cc did you forget to commit something or is this simply not finished?
