### ISSUE TITLE
The graph at the end of viewlets_2 does not render

### ISSUE THREAD

**Issue by fulv** [plone/training#105]
I see from the old site that there is supposed to be a graph on `viewlets_2.html`:
http://plone-training.readthedocs.org/en/latest/viewlets_2.html

But this does not render, locally, or on training.plone.org.
I'm not sure what dependency is missing.

**Comment by pbauer** [comment]
@fulv you need to install graphviz (brew install graphviz on mac, sudo apt-get install graphviz on linux):
    
    WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting

We'll need to update the instruction on how to build the docs locally. But I think more things will need to change when @fredvd starts adding auto-generated screenshots.

**Comment by fulv** [comment]
@pbauer Thanks, it's working now locally.
@svx graphviz needs to be installed on the training.plone.org box.

**Comment by svx** [comment]
graphviz is installed and a new html build [plone5 branch] is pushed to the server, under http://training.plone.org/5/viewlets_2.html I can see now the new 'graphviz image'
