### ISSUE TITLE
PloneFormGen in Plone5 training

### ISSUE THREAD

**Issue by fulv** [plone/training#112]
Currently, after following the instructions on https://github.com/plone/training/blob/master/plone_training_config/instructions.rst, the instance does not start because of PloneFormGen, even though it's using the starzel fork.

Should we leave PloneFormGen out of the training, or do we expect that there will be a Plone5-compatible version?  I could try the 1.8.0-alpha1 version.

Thoughts?

**Comment by smcmahon** [comment]
1.8.x does target Plone 5. alpha 1 installs and passes all its tests except those involving the quickeditor and GS export/import. I expect it to be beta soon, and hopefully ready to release by October.

**Comment by fulv** [comment]
Thanks, @smcmahon.  I tried it and it works.
https://github.com/collective/training_buildout/pull/4
