### ISSUE TITLE
Instructions for Vagrant issue on Windows

### ISSUE THREAD

**Issue by fulv** [plone/training#122]
In plone_training_config/instructions.rst there is the sentence:

```
In Windows there is a bug in the recent version of Vagrant. Here are the instructions for how to work around the warning Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
```

But no link to the promised instructions.

**Comment by spereverde** [comment]
see also https://github.com/plone/training/issues/18
docu was updated, bug no longer there in newer versions
