### ISSUE TITLE
training.plone.org landig page and more

### ISSUE THREAD

**Issue by svx** [plone/training#127]
To get a bit organised, currently we have a 'landing page' on training.plone.org, should this stay in the future and we add more/other trainings, like theming, javascipt, like the trainings of ploneconf2015 and so on ?

Further on, since still some people use also plone 4 do we want to keep it online ? I guess yes, but I want to get feedback.

I will start the next days to update/rebuild training.plone.org, that is the reason why I ask.

**Comment by pbauer** [comment]
The landing page should stay there to link to the 4 and 5 versions of the training. We'll hopefully only have one canonical training (for each version) and try to incorporate topics that are not covered yet (theming, javascript). The danger with separate tranings is that they will probably not be kept up to date and slowly die of bit-rot (like the todo-app or hello-world-tutorial did). We still want to keep the p4 training online with a warning that it includes muss less topics than the p5 one. 

We'll also only cover the lastes version (so no 5.0 when 5.1 is out)

**Comment by stevepiercy** [comment]
Nothing to do here. Closing.
