### ISSUE TITLE
Move training from rtd to training.docs.plone.org or docs.plone.org/training or something else

### ISSUE THREAD

**Issue by svx** [plone/training#14]
During the last year, we worked really hard to get all official docs, out of rtd and other places to have them under one umbrella.
Since training moved to github.com/plone it is also official now and I would like to suggest to move it to for example: training.docs.plone.org or docs.plone.org/training or something else.
This will also make us [Plone] look more professional.

One other reason is, rtd is fine if use 'just' sphinx and buildout, but if you want add robot test [sccreenshots] and auto created translation, this will not work with rtd.

**Comment by svx** [comment]
I can't find the other issue about that, so I will summarize here:

Upcoming new Urls:

training.plone.org/4 -> [Plone 4]

training.plone.org/5 -> [Plone 5]

what should we do with training.plone.org ?

redirect to one of the above or have a landing site saying "Welcome here the link to P4/P5 trainings" ?

@pbauer, @fulv, @fredvd,  and or the rest any thoughts ?

**Comment by fulv** [comment]
I think it should have links to P4 and P5 trainings.

**Comment by svx** [comment]
training.plone.org is online with a landing page and links to the trainings for Plone 4 and Plone 5

**todo**

- upgrade the links in the training docs to point to training.plone,org instead of read the docs
- remove content from read the docs and/or redirect to training.plone.org

**Comment by fulv** [comment]
I think the about.html page is not version-specific, and could be moved to the landing page.  Except that it's a lot of content, and having the landing page be fairly minimal would be a good goal.
The one thing from about.html that should definitely move to the landing page is the "upcoming trainings".    Maybe also "past trainings" and "trainers".

**Comment by svx** [comment]
That is more or less what I did, I also included trainers already.

If we have a list with upcoming traninings sure we can include it

**Comment by fulv** [comment]
I meant 
* http://training.plone.org/4/about.html#upcoming-trainings
* http://training.plone.org/4/about.html#previous-trainings
* http://training.plone.org/4/about.html#trainers

Where does the source for the landing page live?

**Comment by svx** [comment]
As I said, trainers are already included:

http://training.plone.org/trainer/index.html which is a copy of http://training.plone.org/4/about.html#trainers

and sure we can include upcoming and previous trainings.

The source is on github: 

https://github.com/plone/training.plone.org, change it and I will make a new build

**Comment by fulv** [comment]
sorry, missed the link.  I will open pull request.

**Comment by svx** [comment]
IMHO what we all have to keep in mind, that is 'just' a landing page, we do not want to overwhelm the visitor with too much info at all, the visitor is looking for trainings and some info about that.

Also we have to thing as a visitor and not as a developer or trainer.

So we should keep it simple and clear, for more info we can always links to the reference site in the training docs itself.

A good and clear contact info, maybe good, with some info

**Comment by pbauer** [comment]
http://training.plone.org/5/ is the Plone4-version (branch master) and not the Plone5-version (branch plone5).

**Comment by svx** [comment]
Fixed !
