### ISSUE TITLE
no Makefile?

### ISSUE THREAD

**Issue by gforcada** [plone/training#151]
Following the instructions for the Javascript training sent over mail I'm trying to run

``make mockup-minimalpattern``

but there is no Makefile around, maybe there's something that needs to be checkout in src?

@thet

**Comment by thet** [comment]
I've added the Makefile yesterday: https://github.com/collective/training_buildout/blob/master/Makefile
Maybe you don't have an up-to-date buildout?

**Comment by gforcada** [comment]
The branch (plone5) was behind master. It's already fixed :)
