### ISSUE TITLE
unfinished sentence in "7. What’s New in Plone 5" section.

### ISSUE THREAD

**Issue by witekdev** [plone/training#159]
http://training.plone.org/5/plone5.html

In the default theme sub-section:
"If you prefer something a different grid-system (like foundation)" 

Seems like an unfinished sentence, but I don't understand what the original writer was trying to communicate, so I cannot post a direct fix.

**Comment by spereverde** [comment]
this documentation page no longer exists or was updated, no reference to sentence in any existing docu
