### ISSUE TITLE
link to plone_training_config.zip not working in plone4 branch

### ISSUE THREAD

**Issue by deruosi** [plone/training#168]
In the page: http://training.plone.org/4/plone_training_config/instructions.html the link: https://raw.githubusercontent.com/plone/training/master/plone_training_config.zip does not work (404 error)

**Comment by pbauer** [comment]
True. The plone5-training is much more up to date and complete. Most of the content is still true for Plone 4. You can try that until I get around to fixing this.

**Comment by spereverde** [comment]
in the mean time the link has been fixed in the plone 4 training and in the plone training
