### ISSUE TITLE
Upgrade to latest Vagrant and VirtualBox

### ISSUE THREAD

**Issue by fulv** [plone/training#170]
Currently, on http://training.plone.org/5/plone_training_config/instructions.html#install-virtualbox we say **We use VirtualBox 4.3.x**.

Any objections to updating this to the latest?
- VirtualBox 5.0.8
- Vagrant 1.7.4

Personally, I just upgraded my macbook to El Capitan (10.11.1), and found that none of my vagrants were working anymore.  Doing the upgrades above fixed me.  I bet it's possible to make the older versions work on OS X 10.11, but if there is no compelling impediment, we can probably endorse the latest.

**Comment by pbauer** [comment]
:+1:

**Comment by spereverde** [comment]
Documentation was already updated a while ago: https://training.plone.org/5/plone_training_config/instructions.html#install-virtualbox
