### ISSUE TITLE
tango-compiled.css file does not exist

### ISSUE THREAD

**Issue by fulv** [plone/training#173]
I have followed all of http://training.plone.org/5/theming/theme-package.html to the letter, twice, and if the resource registry is not in development mode this error is always logged in the console:

`GET http://localhost:8080/Plone4//++theme++plonetheme.tango/css/tango-compiled.css  404 (Not Found)`

I have built the bundle from the resource registry, as well as with `plone-compile-resources` and `grunt compile-tango-bundle`. What's missing?

**Comment by davilima6** [comment]
This might be related to #174. It seems either your registry.xml or manifest.cfg (or both) defines your tango-compiled.css output to another filename, could you try to locate where it's going in your fs? Also, would you mind pasting the mentioned files?

Also please see plone/Products.CMFPlone#1220 regarding the combination of compiled resources vs devmode vs diazo.

**Comment by fulv** [comment]
I can not find the a css file anywhere in my file system that would result from the compilation of this theme's resources.

I have simply followed http://training.plone.org/5/theming/theme-package.html, so all my files are exactly as they are on that page.  In any case, here they are: https://gist.github.com/fulv/69d4e05a9955e12b1e89

As already discussed elsewhere, this is probably wrong, i.e. using both registry.xml and manifest.cfg.  So I have now deleted registry.xml and installed the theme on a new site.  Supposedly, I should be able to go to the theme editor, open `main.less`, and clicke the `Build CSS` button.  But the dialog just hangs, without any errors in either the shell or the js console, so I'm not sure what it's doing.  And since `manifest.cfg` does not define any bundles, I don't know if there is any way to build from the command line.

**Comment by davilima6** [comment]
@fulv: `./bin/plone-compile-resources` should give you the path where compiled css is, sth like:

```
Running "less:unified-bundle" (less) task
File undefined created.
File /home/davi/Projetos/d11/my.theme/src/my/theme/theme/less/mybundle-compiled.css created
```
Also look for the file in `Products.CMFPlone/static`. Sometimes mine were being compiled there because of some non-identified misconfiguration.

**Comment by davilima6** [comment]
Btw, manifest.cfg does define the implicit "diazo" bundle but since that's not on the configuration registry I guess plone-compile-resource isn't able to reach it.

**Comment by fulv** [comment]
It does not for me, this is the tail of the `plone-compile-resources` output:

```
...
Running "requirejs:tango-main" (requirejs) task

Running "less:tango-bundle" (less) task
>> 1 stylesheet created.
>> 1 sourcemap created.
...
Running "uglify:tango-bundle" (uglify) task
>> 1 sourcemap created.
>> 1 file created.

Done, without errors.
```

But you are right, I found it in `Products.CMFPlone/static/tango-bundle-compiled.css` (note the name is different from the specified name).  (I did not catch it earlier because my buildout-cache is not in the buildout root and I didn't follow sylinks).

The question remains:  how to make the theme find the compiled css?

**Comment by davilima6** [comment]
It's strange that output is more verbose here, maybe it's related to the fact it's not respecting your registry.xml compilation paths. You did reload it after changes, right?

You may pdb on `_generate_gruntfile.py` it to find out why, that's how to make the theme find the css.

Finally I'm not sure an empty value for `last_compilation` is a good idea. Maybe change that to something like yesterday and see if you get different results?

**Comment by stevepiercy** [comment]
Closing as won't fix because this training has been archived.
