### ISSUE TITLE
mailing list mentioned, should be replaced

### ISSUE THREAD

**Issue by jensens** [plone/training#178]
http://training.plone.org/5/add-ons.html#how-to-find-add-ons
here gmane is listed. its should get replaced by community.plone.org

**Comment by imjog** [comment]
Hi @jensens i would like to work on this issue. can i take this?

**Comment by jensens** [comment]
Sure! Since I am not that deep in the training docs I would prefer @pbauer or someone else from the training team to give more guidance.

**Comment by pbauer** [comment]
That has been fixes for some time now. See https://training.plone.org/5/mastering-plone/add-ons.html#how-to-find-add-ons
