### ISSUE TITLE
pdf-build on readthedocs fails

### ISSUE THREAD

**Issue by pbauer** [plone/training#179]
Some people like to use the pdf available on readthedocs but is was really outdated since the build fails. Anyone knows why? E.g. https://readthedocs.org/projects/plone-training/builds/3708102/

I now removed the pdf-build to stop people from using it. Shoud we add a link to a pdf on http://training.plone.org/5/? If yes: How do we build it?

**Comment by svx** [comment]
This has todo with unicode and that someting went wrong with copy and paste, you can see that for example in: https://raw.githubusercontent.com/plone/training/master/theming/theme-package.rst, if you check here the part under _Inspect your package source_ you can see that here something went wrong during copy and paste from the bash tree:

```
$ tree src/plonetheme/tango/
   src/plonetheme/tango/
   ├── browser
   │   ├── configure.zcml
   │   ├── __init__.py
   │   ├── __init__.pyc
   │   ├── overrides
```

If you check this part in your editor you will see that the ```|``` and ```--``` are not good.

By fixing these this will fix at least a couple of the issues :)

**Comment by svx** [comment]
Here is a pic from my editor 

![unicode-pt](https://cloud.githubusercontent.com/assets/358860/12884520/24e8d9f4-ce5f-11e5-85fb-430b28bf5f3c.png)

**Comment by spereverde** [comment]
should I close this or wait until this is tested in the relaunch of this year?
