### ISSUE TITLE
There is a note about a bug in vagrant and windows - but no solution? Missing link?

### ISSUE THREAD

**Issue by Gomez** [plone/training#18]
See:
http://plone-training.readthedocs.org/en/latest/plone_training_config/instructions.html#install-and-configure-vagrant

In Windows there is a bug in the recent version of Vagrant. Here are the instruction how to work around the warning Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.

Link missing?

**Comment by spereverde** [comment]
docu was updated long time ago
