### ISSUE TITLE
Remove <policy name="at_edit_autoversion"/> from dexterity_2.html

### ISSUE THREAD

**Issue by davilima6** [plone/training#184]
iinm This policy should only be used for AT content types.

**Comment by pbauer** [comment]
I think, that is not true. plone.app.versioningbehavior checks for the same policy.

**Comment by davilima6** [comment]
Indeed, sorry. I was deceived by the `at_` prefix, and also by this title in the [related docs](https://github.com/plone/documentation/blob/5.0/develop/addons/components/genericsetup.rst#repositorytool-xml):

    <policy name="at_edit_autoversion"
            title="Create version on edit (AT objects only)"
            class="Products.CMFEditions.VersionPolicies.ATVersionOnEditPolicy"/>
