### ISSUE TITLE
mastering_plone/buildout_1 - Unclear example

### ISSUE THREAD

**Issue by oz123** [plone/training#193]
https://training.plone.org/5/mastering_plone/buildout_1.html#be-mcguyver

The text warns the users about creating too many recipes, and makes a quick mention of
Supervisor without a clear transition to the subject. 

> Supervisor is a program to manage running servers, and it’s pretty good. There is a recipe for it.
> 
> The configuration for this recipe is more complicated than the supervisor configuration itself! By using this recipe, you force others to understand the recipe’s specific configuration syntax and the supervisor syntax. For such cases, collective.recipe.template is a better match.

Maybe this should be re-formulated.

**Comment by do3cc** [comment]
I am not understanding completely.
This paragraph is about debugging and how to avoid pitfalls.
The example of the supervisor recipe clearly states what else to use.

One thing I see from your comment, the warning isn't about using creating too many recipes, but about using too many recipes. And I believe by creating too many recipes you actually meant "creating too many sections" So I see how the beginning of the paragraph could be improved.
