### ISSUE TITLE
Theming chapter: zcml needs some changes to run

### ISSUE THREAD

**Issue by staeff** [plone/training#196]
Hi,

sorry I didn't find a good descriptive Headline for this ticket. From what I know and can say everything is still to fuzzy for me to identify the real problem.
I was going to the "Create a Plone theme python package" section of the Theming chapter.

I was running into a problem on with the configure.zcml file. This file that is created by mrbob looks like this: http://pastie.org/10933402
If I use the file like that, an 'AttributeError: readDataFile' when I test the package. See
http://pastie.org/pastes/10933360/ for full log.
It seems to be related to using the attribute 'post_handler' on registerProfile vs. using the an extra importStep  which runs the post install code.
I took the configure.zcml from the accompanying collective/plonetheme.tango (https://git.io/v6ndD), which fixed the problem.

I added a note how to solve this problem for now to succesfully finish this part of the training (https://github.com/plone/training/pull/197/commits/765df0422e4e272d46d2653518953d8b1827715f). But I think there is a general problem here, which needs to be solved.

**Comment by stevepiercy** [comment]
Closing as obsolete. It is not clear what, if anything, needs to be done. Please reopen with sufficient details to take action.
