### ISSUE TITLE
Responsive menu is broken on small screen

### ISSUE THREAD

**Issue by oz123** [plone/training#198]
The top left "Hamburger" menu doesn't work as expected.

**Comment by stevepiercy** [comment]
What do you see? What do you expect? What is your device and OS?

It works for me, although I notice some issues with the breakpoint at screen widths between 845-1320 pixels. See screenshots.

![google chrome007](https://user-images.githubusercontent.com/102112/48530393-6685bf80-e84c-11e8-8d87-b0dcbce2a30d.png)
![google chrome006](https://user-images.githubusercontent.com/102112/48530394-6685bf80-e84c-11e8-9b64-9b93097d424a.png)
![google chrome005](https://user-images.githubusercontent.com/102112/48530395-6685bf80-e84c-11e8-951f-7872c6881e9e.png)

**Comment by stevepiercy** [comment]
Closing. New theme. This is obsolete.
