### ISSUE TITLE
presentation builder

### ISSUE THREAD

**Issue by svx** [plone/training#200]
It seems I am more stupid than usual, I am not able to find the builder for *make presentation*.

I can find the make option for that

```bash
presentation: *.rst
$(SPHINXBUILD) -b html -t presentation . presentation
```
And I can find the docs:

https://training.plone.org/5/mastering_plone/about_mastering.html#using-the-documentation-for-a-training

But I can't find anything about the setup, nothing in *conf.py* or somewhere else.

**Comment by pbauer** [comment]
`make presentation` works for me. I think it is defined in Makefile.

**Comment by svx** [comment]
@pbauer I am not saying it is not working :)

I can also see the function in the makefile, but I can't find where the builder is coming from, *presentation* is not a default sphinx builder :)

**Comment by svx** [comment]
Never mind, found it, anyway in the meantime I setup my own solution.
