### ISSUE TITLE
How to get started for contributing?

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#237]
I'd like to help on improving the training docs, but there are no instructions in this repo for getting started, including (but not limited to):

1. [x] [How to contribute](https://github.com/blog/1184-contributing-guidelines) See #238
1. [x] Installation requirements
1. [x] How to build the docs and verify locally before making a PR

Perhaps some stuff from [Pyramid](https://github.com/Pylons/pyramid) could be useful?

**Comment by gforcada** [comment]
@stevepiercy thanks for stepping up and wanting to help on this really important subject!!

For 2 and 3, although a bit hidden, if you do what ``.travis.yml`` is doing you should be able to run the tests and thus verify that you have a working copy.

For 1 sending pull requests or adding issues is probably enough, for Plone core we do have some guidelines.

The training team meets every now and then, you can try to reach them here opening issues or discussion broader topics on https://community.plone.org

**Comment by stevepiercy** [comment]
I signed the contributor agreement at PloneConf Boston for all things Plone, so I'm covered.

For 1, I found this https://training.plone.org/about/ I would like to avoid duplicating content. Yet having a `contributing.md` is helpful for folks who use GitHub as an entry point, and informs contributors of what is required. How does this sound: add `contributing.md` with the content:

> Please see our [contributing guidelines](https://training.plone.org/about/).

For 2 and 3 I could do a `HACKING.rst` (or `.txt`, whichever is preferred), [similar to Pyramid's](https://github.com/Pylons/pyramid/blob/master/HACKING.txt), but focused on just building docs locally. What do you think?

**Comment by stevepiercy** [comment]
For 2 and 3, I did the following, but got stuck when the error appeared. I think I need an assist to install pyenchant (or enchant) and whatever else it needs.

```bash
# after creating a Python 2.7.12 virtual environment
$ env27/bin/pip install --upgrade pip wheel setuptools
$ env27/bin/pip install -q -r requirements.txt --use-mirrors
# no such option: --use-mirrors
$ env27/bin/pip install -q -r requirements.txt
$ make html SPHINXBUILD=env27/bin/sphinx-build

/Users/stevepiercy/projects/training/env27/bin/sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.6
making output directory...

Exception occurred:
  File "/Users/stevepiercy/.pyenv/versions/2.7.12/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/stevepiercy/projects/training/env27/lib/python2.7/site-packages/enchant/lib/libenchant.1.dylib, 6): Symbol not found: ___strlcat_chk
  Referenced from: /Users/stevepiercy/projects/training/env27/lib/python2.7/site-packages/enchant/lib/libglib-2.0.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/stevepiercy/projects/training/env27/lib/python2.7/site-packages/enchant/lib/libglib-2.0.0.dylib
The full traceback has been saved in /var/folders/8p/jlq9d1y13ss8q9hb744r6_fr0000gn/T/sphinx-err-eYfOd6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

If I comment out anything to do with spelling in `conf.py`, then I can build the docs.

**Comment by svx** [comment]
You need to install enchant on your OS, looking at your output, it seems to me that your work on macOS ?

So you could use Homebrew and do:

```
brew install enchant
```

or you could use nixpkgs, run it in a container, compile it, or something else :)

Personally I do not install sphinx on my systems anymore, I use you mr.docs [https://mrdocs.readthedocs.io/en/latest/] which is written for docs.plone.org so it/he may miss some settings for training, which is easy to fix :)

I do not know your preference :).

**Comment by stevepiercy** [comment]
I use homebrew on Mac OS X. Installed via `brew install enchant`:

```bash
$ which enchant
/usr/local/bin/enchant
```

But I still get the same error message. I wonder if I installed it via some other method many years ago, like macports, based on this line:

```
  Expected in: /usr/lib/libSystem.B.dylib
```

I don't know how to troubleshoot this further.

Other options are not available to me on this ancient Mac OS X 10.8.5, so I might have to set this aside until I get a new Mac development system set up in a few weeks.

**Comment by gforcada** [comment]
@stevepiercy you can comment out the spelling bits and go on. As long as you create pull requests for all the changes, travis already runs all the checks, so you should be covered there.

Don't make some spelling libraries prevent you to contribute!

**Comment by pbauer** [comment]
@stevepiercy sorry for being late to the party. https://training.plone.org/5/mastering_plone/about_mastering.html#building-the-documentation-locally explains how to build the trainings locally.

Regarding enchant I think you need to create the virualenv and run `pip install -r requirement.txt` **after** installing enchant so that pyenchant can pick it up. Anyway I rarely use `make test` myself and let travis pick up the broken links. I mosty simply run `make html` which tells me about broken rst and builds the docs.

**Comment by stevepiercy** [comment]
D'oh! I just had to read the docs to learn how to build the docs. Thank you!

FTR, I was looking at the root of the repo only to figure out how to build the docs. I assumed that a file at the root is standard practice, based on my experience with projects under the Pylons Project. Would it be appropriate to include a `HACKING` or a mention in the README of where to look to build the docs locally? I'll submit a PR if that is a Plone-y thing to do.

Finally, I threw away my virtual environment, made sure I had enchant already installed, then I [went through the steps to build docs locally again](https://training.plone.org/5/mastering_plone/about_mastering.html#build-new), but still the same error message appears. I have no clue how to troubleshoot this issue. I can just comment out the spelling stuff for now.

**Comment by pbauer** [comment]
The location for the info is due to the historic growt of the project (in the beginning there was only the mastering-plone training in the root and then god created subfolders for other trainings...).
A pull-request would be great. My enchant (Mac Os 10.11.6 with homebrew) works nicely. Simply skip the spelling-stuff.

**Comment by svx** [comment]
If we are talking about it already, it would be nice then to follow our own style guide :) So, please do not create something like 'hacking' create a directory called docs and put it there.

The following step would be to tell sphinx to ignore this directory.

**Comment by stevepiercy** [comment]
@pbauer OK, thanks for the reassurance. Hopefully I can migrate off this old 10.8.5 laptop this weekend to my shiny new 10.11 iMac.

@svx in this case, since it is already documented as @pbauer pointed out, would a link to the relevant passage in the docs added in the `README.rst` be appropriate? I always read a README before hacking. But some projects want to keep minimalist README. FWIW I would not have looked in a subdirectory `docs/` for how to build the docs.

**Comment by svx** [comment]
The way how it should be:

- Update README to follow our official style guide [yes, this includes a link to docs/building, or how you call the file.

As simple as that :)

**Comment by stevepiercy** [comment]
Hey, I'm getting the hang of this Plone community! :)

PR coming.
