### ISSUE TITLE
Master Plone Training inconsistencies with UI

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#247]
Under https://training.plone.org/5/mastering_plone/features.html#users when adding a new user, there are inconsistencies between what the docs state and the Plone UI.

> Make this user with your name an administrator.

and

> Now let’s see the site in 3 different browsers with three different roles:
> 
> * as anonymous
> * as editor
> * as admin

![Add to the following groups:](https://cloud.githubusercontent.com/assets/102112/20639703/bf9c4cfa-b37f-11e6-9af8-d9d31b7f7960.png)

There are two different admin groups and one Reviewer group.

To which admin group should one assign their own user to become an "admin"?

To which group should one assign the `testuser` user to become a Reviewer?

**Comment by fulv** [comment]
Groups and roles are not the same thing.  The UI shown in the registration
form (the screenshot you pasted) shows the groups that Plone comes with out
of the box.  Whereas the training refers to roles.
The three groups you see just happen to have the same names as three of the
available roles.

**Comment by stevepiercy** [comment]
OK, thanks for the clarification. I'll add some stuff to the training instructions to clarify the steps in a PR. Groups appear when creating the user, and roles appear only after creating the first user.
