### ISSUE TITLE
add tutorial on plone.app.discussion

### ISSUE THREAD

**Issue by tkimnguyen** [plone/training#252]
...as per https://community.plone.org/t/forum-board-extension-for-plone/3619/3 and https://github.com/plone/documentation/issues/794

**Comment by MrTango** [comment]
+1 for putting this into the training. We should put it probably into a separate tutorials section.
Because it does not belong to any of the trainings. So a lose collection of tutorial would be probably better.

**Comment by MrTango** [comment]
@pbauer what do you thing about this^^ should we crate a tutorial section in the trainings or maybe separate it into a tutorials repo?

**Comment by svx** [comment]
@MrTango I thought about that, meaning a own repo for tutorials, too.

Pro
===

- Nice, clean own infra, we could even include the video idea from @pigeonflight and lots of existing videos

Con
====
- One more repo :)
- Could get confusing for user ? Well maybe not.

**Comment by MrTango** [comment]
I don't thing that it would be confusing, if we make it clear what is for what.
And link the different parts correctly.

**Comment by svx** [comment]
OK, then I'll create the repo and do the setup of sphinx, tests and so on...

@tkimnguyen would you mind to mail me the original pictures if you still have them ?

Thanks !

**Comment by MrTango** [comment]
maybe wait for @pbauer and others, what they have to say about it.

**Comment by tkimnguyen** [comment]
Yup I'll email you the photos. Let me know where I should start this, though yeah wait for @pbauer et al to chime in.

**Comment by stevepiercy** [comment]
@tkimnguyen I'm closing this issue as stale. Feel free to migrate that tutorial into a new directory under docs/, assuming it is still useful. We now use MyST and Markdown and have a shiny new theme. Let me know if you need any help with that.
