### ISSUE TITLE
Split mastering plone training into 2?

### ISSUE THREAD

**Issue by gforcada** [plone/training#258]
At least visually, or somehow make the 46 chapters in https://training.plone.org/5/mastering_plone/index.html#mastering-plone-label be somewhat *hidden* to feel less intimidating?

At the very top it already says that 1-18 are the beginners training while the others are the advanced.

So maybe if we want to keep it in a single training, put a top-level "Beginners training" and "Advanced training" so that the listings are not so intimidating?

**Comment by svx** [comment]
It gets even better :) currently some of the documents is a chapter are really really long :) 

I am facing that currently with some parts, documents with more than 1000 lines are not ideal :)

I try some stuff to see what is a good and sane way to split these the long documents.

**Comment by gforcada** [comment]
I think some refactoring has happened, so closing this
