### ISSUE TITLE
HTML Syntax highlighting broken with Angular templates

### ISSUE THREAD

**Issue by ebrehault** [plone/training#269]
I have noticed ``.. code-block:: html`` does not produce any highlight if the code contains Angular specific syntax like '*', '[' or ']'.
For instance in this page https://github.com/plone/training/blob/angular/mastering_plone/angular.rst, we have this:
```<li *ngFor="let link of links" [ngClass]="{'active': link.active}">```
And the entire block is not highlighted in the HTML output produced by Sphinx (GitHub seems to support it fine, though).

@svx any idea how to fix that?

Note: the same goes with SCSS blocks, if we keep CSS compliant syntax it works, but as soon as we use nested classes or variables, it breaks.

**Comment by stevepiercy** [comment]
Perhaps the [Angular2HtmlLexer](http://pygments.org/docs/lexers/#pygments.lexers.templates.Angular2HtmlLexer) lexer will do the trick?

There is also [ScssLexer](http://pygments.org/docs/lexers/#pygments.lexers.css.ScssLexer) lexer, which is probably more appropriate than the CSS lexer in use.

**Comment by ebrehault** [comment]
Thanks Steve, I will give it a try.

**Comment by ebrehault** [comment]
@stevepiercy it works great with `scss`, but not with `html+ng2` (for Angular templates) or with `typescript` (instead of javascript). Is there anything special I must do in order to enable a lexer?

**Comment by stevepiercy** [comment]
@ebrehault Pygments must be ≥ v.2.0 for `html+ng2`. Sometimes the version of Sphinx does not pull in the latest Pygments. Or the stylesheet might not have the classes to apply on the rendered markup.

I grabbed your code above and put it into a [Pygments demo](http://pygments.org/demo/6628238/?style=monokai). You might need to tweak the stylesheet to control colors from the rendered markup, shown below:

```html
<div class="hlcode">
  <div class="syntax">
    <pre><span></span><span class="p">&lt;</span><span class="nt">li</span> <span class="p">*</span><span class="na">ngFor</span><span class="o">=</span><span class="s">"let link of links"</span> <span class="p">[</span><span class="na">ngClass</span><span class="p">]</span><span class="o">=</span><span class="s">"{'active': link.active}"</span><span class="p">&gt;</span></pre>
  </div>
</div>
```

Another option would be GitHub gists, as shown in [this article](https://vsavkin.com/angular-2-template-syntax-5f2ee9f13c6a).

**Comment by svx** [comment]
@ebrehault Works for me OOTB, with:

```
.. code-block:: html+ng2
```

Gives me the result:

![angular-lexer](https://user-images.githubusercontent.com/358860/29567824-a8562c52-874e-11e7-8c32-87d29293e049.png)

**Comment by ebrehault** [comment]
cool, thanks :)
