### ISSUE TITLE
Enable Spanish translation for Plone Training from the ReadTheDocs versions

### ISSUE THREAD

**Issue by macagua** [plone/training#273]
Hi @pbauer @do3cc 

The Spanish translation for Plone 4 Training [0] is done and at the moment I have [49% of the translation done](https://www.transifex.com/plone/plone5-training/languages/) of the Plone 5 training.

Then I would like to add the Spanish language as a link to consult from the Plone 4 Training / Plone 5 Training main page documentation at ReadTheDocs.

Please can enable the Spanish translation documentation [0] from ReadTheDocs.org, if you following "Localization of Documentation guide for Project with multiple translations" [1] you need define in the "Plone Training Translations page" [2], that "plone-training-spanish" is a translation for your project.

[0] http://plone-training.readthedocs.io/es/legacy/
[1] http://docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations
[2] https://readthedocs.org/dashboard/plone-training/translations/

**Comment by stevepiercy** [comment]
Because trainings are updated frequently, but not translations, and Google Translate is pretty good, I'm closing this issue as a "won't fix".
