### ISSUE TITLE
Issue with presentation vs no-presentation mode

### ISSUE THREAD

**Issue by svx** [plone/training#277]
There is currently an issue with the following settings:

```
.. only:: presentation
```

and

```
.. only:: not presentation
```

These do not allow you to use code-blocks, which leads to the result that some parts of the docs, which are build with Sphinx for the user or website does not have working lexer, which results to some kind of inconsistency through the docs.

Which may be less important for the 'presenter mode' but which is less ideal for the user/website :)

**Comment by pbauer** [comment]
What is wrong with them? They seem to work fine in https://training.plone.org/5/mastering_plone/buildout_1.html

**Comment by svx** [comment]
Fixed !
Sorry for the noise, the problem was again, that some people check reST against pep8 and what ever and because of this I had to hunt down the 'error' in the syntax, introduced by I guess pep8 or what ever auto-correction. ....

So yeah I used pandoc to transform the created HTML to markdown, run some linter, transform it to reST run some more other linter, correct the last small things from hand and now it is building like it should :)
