### ISSUE TITLE
No matching distribution found for pkg-resources==0.0.0 (new_structure branch)

### ISSUE THREAD

**Issue by jean** [plone/training#278]
https://github.com/plone/training/blob/dd213586dcf8fc4b6e7920967c4558dc6afce202/requirements.txt#L10

```
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 9))
  Downloading MarkupSafe-1.0.tar.gz
Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 10))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 10))
```

**Comment by jean** [comment]
> According to https://github.com/pypa/pip/issues/4022, this is a bug resulting from Ubuntu providing incorrect metadata to pip. So, no there does not seem to be a good reason for this behaviour. I filed a follow-up bug with Ubuntu. https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463

https://stackoverflow.com/a/40167445

**Comment by pbauer** [comment]
removed it.

**Comment by pradityamsook** [comment]
> removed it.

I would tried and it's work.

**Comment by ZLTM** [comment]
To give an actually useful answer, you need to remove the line 'pkg-resources==0.0.0' from requirements.txt, then push the changes to your repository before doing a Heroku push, only removing the line won't work
