### ISSUE TITLE
Error with ng --build

### ISSUE THREAD

**Issue by fulv** [plone/training#280]
@ebrehault 
When I ran `ng build --prod` I got this error:

```
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'
```

Doing `ng build --env=prod` instead, fixed it for me.

I didn't do any of the version upgrades recommended in https://stackoverflow.com/questions/42718095/module-not-found-error-cant-resolve-gendir-app-app-module-ngfactory, though they might be a good idea. 

I have `"@angular/cli": "1.2.3"`, for what it's worth.

**Comment by ebrehault** [comment]
`--prod` and `--env=prod` are different (the first one makes AoT compilation, the second one doesn't)

I will have look
