### ISSUE TITLE
[Matering Plone] Out of Date Info about Heroku

### ISSUE THREAD

**Issue by svx** [plone/training#287]
# Training
Mastering Plone

## Part
Installation/Hosting on with Heroku

### Description
Currently there is *only* the usage of heroku buildpacks mentioned, this is outdated.

Since a couple of weeks Heroku has native Docker support, meaning you can run Plone in a Docker container on Heroku.

You can push your own or even easier you can pull the 'official' Plone Docker container straight from Docker Hub into Heroku.

There is no need anymore to use/handle buildpacks.

### Motivation
I would be nice to mention that in the training in one line, since that is a great solution for people who already using docker because it lowers the barrier.

**Comment by tkimnguyen** [comment]
It would be better to keep all installation options for Plone in one place, in plone.org/download
