### ISSUE TITLE
Broken link to Content Management on live https://training.plone.org/ 

### ISSUE THREAD

**Issue by jensens** [plone/training#329]

**Comment by ramiroluz** [comment]
I believe it is fixed.

**Comment by gforcada** [comment]
The link works, but it points to a generic overview of the trainings, whereas the other trainings point to their specific overview.

Looking at the overview where it points now, I don't see where that should like, @pbauer is some training lost or well hidden somewhere? :thinking: :mag:

**Comment by bvishal8510** [comment]
@jensens can you tell me where this broken link is present?

**Comment by jensens** [comment]
The link points to https://training.plone.org/5/ instead to a site covering the proposed topic "Content Management - How to work with content and manage site settings in Plone."
![screenshot at 2019-01-14 17-51-09](https://user-images.githubusercontent.com/157140/51127147-18c60d00-1825-11e9-9636-e1aa92fedb6e.png)

**Comment by bvishal8510** [comment]
Thank u @jensens  for an explanation but I was asking for the location of the file in which link needs to be changed to make it correct.

**Comment by ramiroluz** [comment]
@bvishal8510 I think it is here: https://github.com/plone/training.plone.org/blob/master/data/features/content_management.yaml

**Comment by jensens** [comment]
I fixed this in the other repository, deployment is pending.
