### ISSUE TITLE
Uploads to dist.plone.org for 5.1.4

### ISSUE THREAD

**Issue by tschorr** [plone/training#340]
If we want to use Plone 5.1.4 for the training, somebody with write access to dist.plone.org needs to upload a `requirements.txt` and the buildout-cache tarball:

http://dist.plone.org/release/5.1.4/requirements.txt
http://dist.plone.org/release/5.1.4/buildout-cache.tar.bz2

These files are needed for the Vagrant setup.

**Comment by tschorr** [comment]
@svx fine thx I'll prepare them for tomorrow. The buildout cache tarball is going to be ~60M in size. I intend to provide it in a gist, are you OK with that?

**Comment by svx** [comment]
As far as I can "just" pick stuff (download) and upload I am fine with what ever works for you :)

**Comment by svx** [comment]
@tschorr there is already a requirements.txt in /release/5.1.4 should we do something like /release/5.1.4/training and put the file there ? or maybe /release/training ?

**Comment by svx** [comment]
@tschorr ok so for now only the buildout-cache, right ?

**Comment by svx** [comment]
done !

**Comment by tschorr** [comment]
@svx I tried and it worked once but now I see again a 404 when I try to open http://dist.plone.org/release/5.1.4/buildout-cache.tar.bz2

**Comment by svx** [comment]
The file is on the machine, but it looks like there is something with the box. It is working but super slow.

Looks like something with the machine, nothing I can do about :(

I only can offer to upload to archive.plone.org

**Comment by pbauer** [comment]
@esteele: any idea what might be wrong?

**Comment by esteele** [comment]
I can see the files and downloads are a bit slow for me, but not horribly so.

**Comment by tschorr** [comment]
Everything works as expected now. Thanks everybody!
