### ISSUE TITLE
Javascript training has outdated setup infos

### ISSUE THREAD

**Issue by pnicolli** [plone/training#344]
The JavaScript for Plone Developers training [setup section](https://training.plone.org/5/javascript/training-installation.html) has a link to a [training buildout](https://github.com/collective/training_buildout), and it says the buildout should have an `auto-checkout` configuration for `mockup`, but it doesn't have it anymore.
I could add that back to the buildout in order to have it for future trainings. Another option would be to create a new buildout just for that training purposes, since the one linked above is meant to be used for another training.
What do you think? What should I go for?

**Comment by pbauer** [comment]
I think that is outdated and 5.1.4 has a new enough version of mockup.

**Comment by pnicolli** [comment]
#409 and https://github.com/collective/collective.jstraining/pull/3 should fix this issue.

**Comment by pnicolli** [comment]
Fixed with aforementioned PRs
