### ISSUE TITLE
Add cookiecutter template to training writing guide

### ISSUE THREAD

**Issue by svx** [plone/training#345]
https://github.com/testthedocs/cookiecutter-plone-training

Needs some fixing and a bit more polishing, but after that we should add it it to the docs part on how to get started with writing training docs.

**Comment by svx** [comment]
Update: I fixed the issues with https://github.com/testthedocs/cookiecutter-plone-training, so far so good ...

**Comment by stevepiercy** [comment]
This cookiecutter is now obsolete. Closing.
