### ISSUE TITLE
Add support for jsx-lexer

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#347]
We've got at least three trainings that could use `jsx` as a lexer via [jsx-lexer](https://github.com/fcurella/jsx-lexer). This lexer works with other themes, but not the RTD theme.

See https://github.com/plone/training/pull/341#issuecomment-434638732

I have no idea whether it is possible to customize the RTD theme for lexers not included with Pygments.

Filed ticket upstream on 2024-11-07 in https://github.com/pygments/pygments/issues/2816.

**Comment by sneridagh** [comment]
+1 also we need to add a less lexer too!

@svx do you think it's possible?

**Comment by stevepiercy** [comment]
I just ran a test, and it appears that both the default and RTD themes lack sufficient styling to make jsx-lexer useful. But there is an [open PR upstream in Pygments](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/722/close-1002-add-jsxlexer/diff)

**Comment by stevepiercy** [comment]
We now have a JSX, LESS, and SCSS lexers with the new theme. However, the JSX is not that great. We might need to use JS or plain old `text`.

**Comment by stevepiercy** [comment]
When writing JSX code, avoid using `'` in HTML tags. The lexer barfs on it.

**Comment by stevepiercy** [comment]
See https://github.com/fcurella/jsx-lexer/issues/15
