### ISSUE TITLE
Volto - Bootstrapping Plone

### ISSUE THREAD

**Issue by cekk** [plone/training#348]
In the chapter 3, you say that we need a working Plone instance.
Maybe there are some students that don't know what exactly they need to do.

I tried with a Plone 5.1.4, but i needed to add some extra informations:
- plone.restapi
- a Plone site with a specific name (Plone) that responds to 8080 port with plone.restapi installed
- a conf in instance part to avoid CORS problems

Could it be useful for the students, a link to volto /api section where there are a buildout and docker image ready-to-go? And maybe some infos about how to bootstrap it?

**Comment by stevepiercy** [comment]
Closing as won't fix because this training has been archived.
