### ISSUE TITLE
[Mastering Plone] - grep command on exercise is correct?

### ISSUE THREAD

**Issue by ramiroluz** [plone/training#383]
Chapter 30. Turning Talks into Events.

The solution for Exercise 1 suggests a grep command:
``$ grep -sirn --include \*.zcml 'name="event_summary"' ./packages``

The command returned nothing for me, my SO is Linux, debian distribution. Instead I had to run:
``$ grep -siRn --include \*.zcml 'name="event_summary"' ./packages``

The first command works on other systems?

**Comment by pbauer** [comment]
It works on my mac, but `R` does the same according to my manpage so we should change it to `R`

**Comment by ramiroluz** [comment]
Fixed, did a pull request #386. Forgot to put a hook there. So this issue must be closed "by hand".

**Comment by stevepiercy** [comment]
Closed by #386
