### ISSUE TITLE
Travis CI build succeeds on PR, fails on merge

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#410]
This PR passed the Travis CI build:
https://travis-ci.org/plone/training/builds/514900652

After I merge it, this Travis CI build failed:
https://travis-ci.org/plone/training/builds/514936740

Can anyone explain how the exact same code would both succeed and fail? Are there two different build pipelines in place? The settings don't offer a clue:
https://travis-ci.org/plone/training/settings

**Comment by stevepiercy** [comment]
@pbauer is `ploneconf.site_sneak` still in use, or should it be removed from the training docs? There are numerous errors in Sphinx:

```
mastering-plone/testing.rst:153: WARNING: Include file u'ploneconf.site_sneak/chapters/02_export_code_p5/src/ploneconf/site/tests/test_talk.py' not found or reading it failed
mastering-plone/testing.rst:161: WARNING: Include file u'ploneconf.site_sneak/chapters/03_zpt_p5/src/ploneconf/site/tests/test_talk.py' not found or reading it failed
mastering-plone/testing.rst:186: WARNING: Include file u'ploneconf.site_sneak/chapters/final/src/ploneconf/site/tests/test_talk.py' not found or reading it failed
mastering-plone/testing.rst:196: WARNING: Include file u'ploneconf.site_sneak/chapters/03_zpt_p5/src/ploneconf/site/tests/robot/test_talk.robot' not found or reading it failed none found
```

**Comment by pbauer** [comment]
It should be removed. it was used to pull in code but that is outdated.

**Comment by stevepiercy** [comment]
OK, I just commented out those literalincludes. That chapter needs some tender luvin'.

I made additional fixes, too.

The only thing that I didn't fix was syntax highlighting for the following languages: html+ng2, scss, http, js, less, jsx. All except jsx are [valid lexers in Pygments](http://pygments.org/docs/lexers/). I'm not sure what is a good replacement for them.
