### ISSUE TITLE
React: initial generated code differs

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/training#421]
The initial code from the `create-react-app` call in the training docs, shows a class that extends `Component`. See https://training.plone.org/5/react/component.html

What I get instead, is a function:

```
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

I don't know which one is better. I see two options:

1. Switch the training to use a function.
2. Explain why the training does this differently.

Some version numbers:

```
$ nvm --version
0.34.0
$ yarn --version
1.17.3
$ npm --version
6.9.0
$ node --version
v10.16.3
$ cat package.json 
...
  "dependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "3.1.1"
  },
...
```

**Comment by mauritsvanrees** [comment]
Functions are apparently the new way, so the training should be updated to reflect this.

**Comment by avimishra18** [comment]
React training only uses functional components as of now. I think this issue can be closed. 🙂

**Comment by stevepiercy** [comment]
Closing as won't fix because this training has been archived.
