### ISSUE TITLE
React: should files have suffix .jsx?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/training#422]
The solution for the exercise in paragraph [7.2](https://github.com/plone/training/blob/master/react/state.rst) shows the diff for a file named `FaqItem.jsx`. In my case I have file `FaqItem.js` without an `x`, so I am mildly surprised.

Does the suffix matter?  If so, [chapter 5](https://github.com/plone/training/blob/master/react/reusable_component.rst) should tell me to create the file with this extension.

**Comment by avimishra18** [comment]
### Does the suffix matter? If so, chapter 5 should tell me to create the file with this extension.

Check the [react-scripts config](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpack.config.js) which is used in [create-react-app](https://create-react-app.dev/)
```
  // Process application JS with Babel.
  // The preset includes JSX, Flow, TypeScript, and some ESnext features.
  {
    test: /\.(js|mjs|jsx|ts|tsx)$/,
    include: paths.appSrc,
    loader: require.resolve('babel-loader'),
    options: {
      customize: require.resolve(
        'babel-preset-react-app/webpack-overrides'
      ),
      presets: [
        [
          require.resolve('babel-preset-react-app'),
          {
            runtime: hasJsxRuntime ? 'automatic' : 'classic',
          },
        ],
      ],
```
It supports both `.js` & `.jsx` extensions & possibly handles them the same way in this case. So, the extension of the file shouldn't matter here. Projects not using the same configuration might have the feature that prevents from writing JSX in files having the `.js` extension.


### The solution for the exercise in paragraph [7.2](https://github.com/plone/training/blob/master/react/state.rst) shows the diff for a file named FaqItem.jsx. In my case I have file FaqItem.js without an x, so I am mildly surprised.

Yes, the `.jsx` extension is used in several places currently: 

- [9.1. Toggle Function](https://training.plone.org/5/react/event_handlers.html#toggle-function)
- [10.1. Add Delete Button](https://training.plone.org/5/react/callbacks.html#add-delete-button)
- [12.2. Wiring Everything Together](https://training.plone.org/5/react/initial_form_data.html#wiring-everything-together)
- [15. Use Actions To Manipulate The Store](https://training.plone.org/5/react/actions.html#use-actions-to-manipulate-the-store)
- [19. Using Links To Navigate](https://training.plone.org/5/react/links.html#using-links-to-navigate)
- [20. Navigate Using Redirects](https://training.plone.org/5/react/redirects.html#navigate-using-redirects)

**I am interested in fixing this issue if I get a go-ahead from community members. 😄**

**Comment by avimishra18** [comment]
@stevepiercy can I assign myself this issue?

**Comment by stevepiercy** [comment]
@avimishra18 sure. I am not familiar with this content, but the current assignees may be able to advise and direct you. @jaroel @robgietema

**Comment by mauritsvanrees** [comment]
I see that the training has been updated, and the links in the issue do not exist anymore. Let me add links that work today.

This is the React training: https://training.plone.org/5/react/index.html
What above is chapter 5 is now 6, and chapter 7 is 8.
My problem at the time was in these two links, using the GitHub sources here:

- chapter 5/6 on [reusable components](https://github.com/plone/training/blob/main/docs/react/reusable_component.md)
- chapter 7/8 on [how to use state](https://github.com/plone/training/blob/main/docs/react/state.md)

I have no idea if it is better to use `.js` or `.jsx` as suffix. But my problem was: one chapter was telling me to create a file `FaqItem.js` and another chapter made some changes and showed a diff for a file named `FaqItem.jsx`. They should both have used the same file name.

When I look at the two chapters now, they both use `.jsx` as suffix. So this problem has meanwhile been fixed.

Thanks to whoever did this!
And thank you @avimishra18 for offering to solve it.

There might be similar problems left, so maybe you can still fix something, which would be good. But since the immediate problem is already solved, I will close it.
