### ISSUE TITLE
React 14.3 Excercise: arguments for connect are not explained

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/training#434]
This is the end of the solution for exercise 14.3:

```
export default connect(
  () => ({}),
  { editFaqItem, deleteFaqItem }
)(FaqItem);
```

I don't understand why the first argument to `connect` is so empty. I would have expected it to get some state and props (index, question, answer), and return at least `{index}`, because `index` ends up in the props. The code works, but I don't yet understand why.
Maybe this will be explained in live training.

**Comment by mauritsvanrees** [comment]
Rob explained that this is because we already get those properties from `Faq.jsx`:

```
            <FaqItem
              question={item.question}
              answer={item.answer}
              index={index}
            />
```

Technically we could pass only `index` here, and then in the `connect` call use this index to get the question and answer from the store.

**Comment by avimishra18** [comment]
React training only uses functional components. I think this issue can be closed.

**Comment by stevepiercy** [comment]
Closing as won't fix because this training has been archived.
