### ISSUE TITLE
Update solr training

### ISSUE THREAD

**Issue by reinhardt** [plone/training#475]
The solr training is out of date and doesn't work as described any more, e.g. because collective.solr uses kitconcept.recipe.solr instead of collective.recipe.solrinstance now.

**Comment by reinhardt** [comment]
I'll try looking into it today.

**Comment by reinhardt** [comment]
First step was done in #476. The first couple of chapters have mostly been brought up-to-date, up to and including "Solr Buildout Configuration". The remaining chapters still have some references to c.recipe.solrinstance. In the setup part, `bootstrap-buildout.py` should be replaced with `venv` and `pip install`.

**Comment by stevepiercy** [comment]
@reinhardt we've migrated from using rST to MyST. We would accept a PR that addresses this issue.

FWIW I recently updated all the links per the split between Lucene and Solr.

**Comment by stevepiercy** [comment]
Closing as won't fix. The solr training is now archived.
