### ISSUE TITLE
Add Sphinx-copybutton extension to copy code with a click

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#490]
As a fellow trainer who stumbled with correct copy-paste mousing dexterity on occasion, I decided to install this in the Pyramid docs.

https://sphinx-copybutton.readthedocs.io/en/latest/

Would this be useful, and if so would you accept a PR for the Plone Training docs?

**Comment by ksuess** [comment]
Sorry for liking but without any further action.
Copy button is now part of future PR of branch https://github.com/plone/training/tree/ksuess-theme-playground
