### ISSUE TITLE
Add some SEO info with `html_meta` directive

### ISSUE THREAD

**Issue by ksuess** [plone/training#519]
at least for the intro chapters of each training

```
---
html_meta:
  "description": "directives and other examples in markdown / mySt"
  "keywords": "Sphinx, MyST, markdown"
---
```

to be inserted at the beginning of a page

**Comment by stevepiercy** [comment]
I think we covered this in https://training.plone.org/5/contributing/authors.html#html-meta-data

See also https://github.com/plone/training/issues/529

**Comment by ksuess** [comment]
Why not adding a check of every 2021 chapter on existence of html_meta description in PR test?

**Comment by stevepiercy** [comment]
> Why not adding a check of every 2021 chapter on existence of html_meta description in PR test?

Because I do not know where to begin to write such a test.

I guess we could add a task to `Makefile` that recursively scans the `docs` directory for `.md` files, puts them into a list, then iterates over the list to check each file for the presence of the string:

```rest
---
html_meta:
  "description":
```

**Comment by stevepiercy** [comment]
Can this issue be closed now with the merge of #538?

**Comment by ksuess** [comment]
I thought to leave it as a reminder to check if text is filled in at least for meta tag "description" at least for each trainings start pages.

**Comment by stevepiercy** [comment]
`make clean html`

```console
docs/index.md:: WARNING: Error parsing meta tag attribute "description": No content.
docs/index.md:: WARNING: Error parsing meta tag attribute "property=og:description": No content.
docs/index.md:: WARNING: Error parsing meta tag attribute "property=og:title": No content.
docs/index.md:: WARNING: Error parsing meta tag attribute "keywords": No content.
```

I see plenty of reminders. 😉

**Comment by ksuess** [comment]
So closing this reminding reminder on reminders
