### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#533]
Consider adding a dark mode for usability.

https://github.com/executablebooks/sphinx-book-theme/issues/265

**Comment by stevepiercy** [comment]
Progress is being made on a [PR in the pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme/pull/540) on which sphinx-book-theme is based. If you have feedback, please let them know.

**Comment by stevepiercy** [comment]
And now it is in progress in https://github.com/executablebooks/sphinx-book-theme/pull/574

**Comment by stevepiercy** [comment]
This also includes the new announcement banner feature that is required in https://github.com/plone/training/issues/672

**Comment by rakshith6404** [comment]
As i raised the issue on the same,i Would like to work on Add dark mode which i am currently going through the methods that were used in pydata and sphinx to create a dark mode.

**Comment by stevepiercy** [comment]
@rakshith6404 please see https://6.docs.plone.org/contributing/#making-contributions-on-github, specifically Item 2. 😁

**Comment by rakshith6404** [comment]
I have pretty much went through the contributing guidelines long back :smile:

**Comment by stevepiercy** [comment]
Closed by #752
