### ISSUE TITLE
pyenv virtualenv 3.9.5 plonepy result pyenv: no such command `virtualenv'

### ISSUE THREAD

**Issue by mactrash** [plone/training#535]
I am new to this, I can't follow the steps to install python

**Comment by stevepiercy** [comment]
What did you try? Which steps? Please provide a link to the steps that you mention.

**Comment by mactrash** [comment]
<img width="814" alt="Screenshot 2021-09-18 at 6 52 42 AM" src="https://user-images.githubusercontent.com/1506388/133861615-fd07e366-6551-496a-b6ba-ba0dbe9efb56.png">
Many thanks

**Comment by stevepiercy** [comment]
Screenshots don't help. We need a link.

Do you have pyenv installed to manage your various Python versions?

**Comment by mactrash** [comment]
@stevepiercy yes pyenv install 3.9.5 run success

**Comment by ksuess** [comment]
The pyenv plugin "pyenv-virtualenv" is not installed. You can 
- install it into your existing pyenv or 
- run the pyenv installer mentioned in the training chapter which installes pyenv with plugins.

**Comment by stevepiercy** [comment]
@mactrash I'm going to close this issue, assuming that you were able to resolve it because you have not provided further information. Feel free to reopen it, or post your question to the [Community forum](https://community.plone.org/).
