### ISSUE TITLE
Use Plone 5 in the training

### ISSUE THREAD

**Issue by pbauer** [plone/training#54]
Todo:
- [x] use Plone 5 in the vagrant-setup
- [x] update the training-buildout. Started in https://github.com/collective/training_buildout/tree/plone5
- [x] replace zopeskel with mr.bob. Started in: https://github.com/collective/bobtemplates.plone
- [x] Make add-ons compatible with Plone 5 
  - [x] ploneconf.site
  - [x] Products.PloneFormGen 
  - [ ] collective.plonetruegallery
  - [ ] collective.behavior.banner
- [ ] update training-documentation

**Comment by tkimnguyen** [comment]
Can we close this? I think it's safe to say that we have been using P5 in the training...
