### ISSUE TITLE
Update training "Volto": "Bootstrapping a project" 

### ISSUE THREAD

**Issue by ksuess** [plone/training#563]
`npx @plone/create-volto-app my-volto-app` is outdated

https://training.plone.org/5/volto/bootstrap.html#bootstrapping-a-project

**Comment by wesleybl** [comment]
When using the current documented way of creating the `Volto` project, that is:

```
npx @plone/create-volto-app my-volto-app
```
The following error occurs when trying to start the server:

```
TypeError: _plone_volto_config__WEBPACK_IMPORTED_MODULE_1__.addonRoutes is not iterable
```

See: https://github.com/plone/volto/issues/3228

**Comment by stevepiercy** [comment]
@wesleybl we would greatly appreciate a pull request from you to fix the instructions, especially since you figured out the solution.

**Comment by stevepiercy** [comment]
@ksuess why? Is it not OK to encourage contributors to make corrections? Please explain.

**Comment by wesleybl** [comment]
> @wesleybl we would greatly appreciate a pull request from you to fix the instructions, especially since you figured out the solution.

Yes @stevepiercy . As soon as I have some time I'll do a PR.
