### ISSUE TITLE
TOBEDISCUSSED mandatory linkcheck for deployment

### ISSUE THREAD

**Issue by ksuess** [plone/training#574]
linkcheck is important but blocks from time to time a deployment.

**Comment by stevepiercy** [comment]
I was just discussing this with @tkimnguyen in Discord not too long ago. He mentioned that he had some problems setting up the local dev environment to build the docs and run `make linkcheck`, but did not elaborate on how to improve our setup docs.

Anyway, I think that the `test` GitHub Action should be broken into two different tasks: `linkcheck` and `spellcheck`. It will make finding mistakes easier. It will also run jobs in parallel, speeding up the test processes.

I see two questions:

1. What do we do when a link breaks?
    a. Nothing. This leads to bitrot. I do not like this option.
    b. Update the link to something useful, even if it is on https://archive.org/.
    c. Delete the link.

2. Who is responsible for maintaining the links when they break?
    a. Original author who wrote the link, using `git blame`. This option is not good. It could mean hunting down someone who might have moved on and has no interest in updating it (for example, the WSGI training).
    b. Core Training docs maintainers. We already do too much!
    c. Person submitting a PR where broken links are exposed, either as part of their PR or not. If the person submitting the PR breaks a link, they should definitely fix it. But if their PR is unrelated to the broken link, it sure would be nice for them to also update the broken links while they are in there. This helps spread the burden of maintaining links.

Unfortunately we have a culture in Plone of doing nothing when links break. Do we want to change that? Am I the only person who cares enough to do anything about it?

**Comment by tkimnguyen** [comment]
I just hadn't gotten around to figuring out what my local setup problem was. I didn't follow the page of setup instructions you referred to. I just tried to setup sphinx and the required myst parser the way I usually do: stumbling...

I dislike the links to external information because of bistrot. So many blog posts etc we currently point to in the main docs are now gone. I think if the information being linked to is important, we should include it right in our own material (and leave the link as a credit/reference).

**Comment by ksuess** [comment]
Great input and base for discussion. That's why I opened the issue and Plone is evolving. Please let's think about and come back to it.

Now I need to maintain the training docs. And the linkchecker is in my way. So will disable the linkcheck now, temporarily.

**Comment by stevepiercy** [comment]
> So many blog posts etc we currently point to in the main docs are now gone. I think if the information being linked to is important, we should include it right in our own material (and leave the link as a credit/reference).

I think we already do this, but we should definitely include this point in our [Authors Guide](https://training.plone.org/5/contributing/authors.html).

As far as what kinds of links go bad:

- Blog posts
- Deep links to specific sections in external documentation
- VirtualBox.org, again!
- Rate limiting (GitHub especially)

I could write something up that is more guideline-ish for the Authors Guide.

What is your opinion about links that exist and go bad? Who should fix them?

**Comment by stevepiercy** [comment]
> Anyway, I think that the `test` GitHub Action should be broken into two different tasks: `linkcheck` and `spellcheck`. It will make finding mistakes easier. It will also run jobs in parallel, speeding up the test processes.

See [PR #578](https://github.com/plone/training/pull/578).

> I could write something up that is more guideline-ish for the Authors Guide.

Actually I already did this: https://training.plone.org/5/contributing/authors.html#all-links-must-be-valid

As far as any other actionable items in this issue, the only one is to restore the enforcement of linkcheck when @ksuess is done with her work.

**Comment by ksuess** [comment]
@stevepiercy, please reopen if you think it is still relevant.

**Comment by stevepiercy** [comment]
Nope, we're good. linkcheck is re-enabled.

One more thing to notice, I made some [changes to the Sphinx configuration in Documentation](https://github.com/plone/documentation/commit/b000ae85b6af6cf3bb56787ff5f500af002704b7) that are worth consideration for Training. There are some pages with anchors that fail because ~~JavaScript sucks~~ of SSR or other silliness that Sphinx cannot handle. What do you think about changing the Training config?

**Comment by ksuess** [comment]
yes, good idea. I just now experienced the case that a merge in main failed on link checks, but succeeded on a re-run. So, yes, a linkcheck_retries=2 is an enhancement.
