### ISSUE TITLE
Documentation of Deployment Options is Suboptimal

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#577]
See also #566.

There are four trainings that relate to deployment.

| Name/Link | Location | Author | Base | Plone Version |
| --- | --- | --- | --- | --- |
| [Automating Plone Deployment](https://training.plone.org/5/deployment/index.html) | `deployment` | @smcmahon | Ansible | 5, 6 classic? |
| [Plone Deployments With Amazon OpsWorks](https://training.plone.org/5/deployment/opsworks/index.html) | `deployment/opsworks` | @alecpm | Amazon OpsWorks | 5, 6 classic? |
| [Plone Deployment](https://training.plone.org/5/plone-deployment/index.html) | `plone-deployment` | @ericof | Docker | 6 |
| [Deploying and Operating Plone on WSGI](https://training.plone.org/5/wsgi/index.html) | `wsgi` | @tschorr | buildout | 5, 6 classic? |

"Automating Plone Deployment" is based on [Plone’s Ansible Playbook](https://plone-ansible-playbook.readthedocs.io/en/latest/intro.html) [repo](https://github.com/plone/ansible-playbook) and [ansible.plone_server](https://github.com/plone/ansible.plone_server).

First some reorganization needs to take place. Here are my suggestions.

- OpsWorks should be promoted to the root level.
- `opsworks` should be rename to `deployment-opsworks`
- `deployment` should be renamed to `deployment-ansible`
- `plone-deployment` should be renamed to `deployment-docker`
- `wsgi` should be renamed to `deployment-wsgi` or `deployment-buildout`

~~Second we need to decide what makes the cut for version 6.~~

~~Finally the content of each training that makes the cut needs to be updated and edited.~~ Edit: see #672

I'd appreciate any comments.

**Comment by Coder-aadarsh** [comment]
Hm .... It sounds like you have some good suggestions for reorganizing and renaming the Plone deployment trainings. I agree that OpsWorks should be promoted to the root level and that the other trainings should be renamed to better reflect their deployment methods.

Regarding what makes the cut for version 6, that would depend on the specific changes and updates made to Plone in that version.

**Comment by stevepiercy** [comment]
What makes the cut is now in its own issue, and it is in progress: https://github.com/plone/training/issues/672

Reorganization of the deployment trainings still needs to happen. A PR to make that happen would be greatly appreciated.

**Comment by stevepiercy** [comment]
Closing as won't fix.
