### ISSUE TITLE
buildout:eggs is a bad idea

### ISSUE THREAD

**Issue by jensens** [plone/training#59]
At https://github.com/plone/training/blob/plone5/buildout_1.rst eggs are defined in the buildout section and then used with ${buildout:eggs} in instance. 

This will lead to serious problems if you start building eggs like i.e. python-ldap with custom options. I wrote a blog entry about it in 2008 http://bluedynamics.com/articles/jens/dependencies-and-zc.buildout which is still true.

**Comment by aclark4life** [comment]
+1000 Pretty sure I've written about this too, and could dig up some blog entries about it if needed.

**Comment by aclark4life** [comment]
E.g. you will never see `buildout:eggs` in Plock: https://github.com/plock/pins
