### ISSUE TITLE
Issue on page /react/routes.html [18. Using Different Routes]

### ISSUE THREAD

**Issue by avimishra18** [plone/training#592]
# Issue
[react-router-dom](https://www.npmjs.com/package/react-router-dom) package had a major update from v5 to v6. It has a lot of breaking changes. [18. Using Different Routes](https://training.plone.org/5/react/routes.html) was written at the time of v5. But the command: 
```
yarn add react-router-dom
```
Mentioned [here](https://training.plone.org/5/react/routes.html#routing) will install the latest version i.e. v6 now.

[Link to Community Discussion](https://community.plone.org/t/information-for-interested-gsoc-students-2022/14893/14?u=avimishra18). Assigning this issue to myself.

# Possible Solution

There can be two approaches to deal with the issue. Requesting community members to give their valuable guidance in selecting the correct approach.

## Approach 1 (Pinning major version to v5)
We can be specific about the version. And update the command to: 
```
 yarn add react-router-dom@^5.0.0 
 ```

## Approach 2 (Migration from v5 to v6)
We can update the documentation following steps mentioned in the official documentation of react-router-dom: [Migration to v6](https://reactrouter.com/docs/en/v6/upgrading/v5). Some, changes that needs to take place: 

**Format:** `v5 code` => `v6 code`
1. `<Routes component={Component}/>` ⇒ `<Route element={<Component/>}/>`
1.  `useHistory()` ⇒ `useNavigate()`

**Comment by stevepiercy** [comment]
For this one, I would check with the Volto frontend folks if they have future plans to migrate to v6. For the upcoming v15.0 release, it is at [`5.2.0`](https://github.com/plone/volto/blob/master/package.json#L383).

**Comment by avimishra18** [comment]
@nileshgulia1 @TC5022

**Comment by TC5022** [comment]
Thank you @avimishra18 
@stevepiercy Should I go ahead and update v5 to v6?

**Comment by nileshgulia1** [comment]
@TC5022 As steve said, you can start the conversation at https://github.com/plone/volto by creating an issue, followed by a nice PR.

**Comment by TC5022** [comment]
@stevepiercy @nileshgulia1 Got it! Thank you for your guidance 💯
