### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by ksuess** [plone/training#604]
same for plone/documentation

**Comment by ksuess** [comment]
Request update of https://plone.org/foundation/copyright-licensing-logo/license-faq for documentation and training.

**Comment by stevepiercy** [comment]
`plone/documentation` is fine:

- https://github.com/plone/documentation
- https://6.dev-docs.plone.org/contributing/index.html#granting-permission-to-publish

I think you can close this issue, and open one under `plone/plone.org` for updating the page to include an exclusion for anything doc-ish.

**Comment by stevepiercy** [comment]
This is covered on https://plone.org/foundation/copyright-licensing-logo/plone-documentation-licensing-faq
