### ISSUE TITLE
Error when provisioning machine from zip file (pkg_resources.VersionConflict: (setuptools 2.2 (/home/vagrant/py27/lib/python2.7/site-packages), Requirement.parse('setuptools>=8.0')))

### ISSUE THREAD

**Issue by idgserpro** [plone/training#61]
Just by provisioning the machine [from the zip in the official docs](https://plone-training.readthedocs.org/en/latest/_downloads/plone_training_config.zip) this error occurs:

```
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "bootstrap.py", line 159, in <module>
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     ws.require(requirement)
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "/home/vagrant/py27/local/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     needed = self.resolve(parse_requirements(requirements))
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "/home/vagrant/py27/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     raise VersionConflict(dist,req) # XXX put more info here
==> default: Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: pkg_resources.VersionConflict: (setuptools 2.2 (/home/vagrant/py27/lib/python2.7/site-packages), Requirement.parse('setuptools>=8.0'))
==> default: Notice: /Stage[main]/Plone/Exec[/vagrant/buildout/bin/buildout]: Dependency Exec[/home/vagrant/py27/bin/python bootstrap.py] has failures: true
==> default: Error: /home/vagrant/py27/bin/python bootstrap.py returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: change from notrun to 0 failed: /home/vagrant/py27/bin/python bootstrap.py returned 1 instead of one of [0]
==> default: Warning: /Stage[main]/Plone/Exec[/vagrant/buildout/bin/buildout]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 9.66 seconds
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --manifestdir /tmp/vagrant-puppet-9/manifests --detailed-exitcodes /tmp/vagrant-puppet-9/manifests/plone.pp

Stdout from the command:

Notice: Compiled catalog for training.plone.org in environment production in 0.06 seconds
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: Traceback (most recent call last):
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "bootstrap.py", line 159, in <module>
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     ws.require(requirement)
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "/home/vagrant/py27/local/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     needed = self.resolve(parse_requirements(requirements))
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:   File "/home/vagrant/py27/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns:     raise VersionConflict(dist,req) # XXX put more info here
Notice: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: pkg_resources.VersionConflict: (setuptools 2.2 (/home/vagrant/py27/lib/python2.7/site-packages), Requirement.parse('setuptools>=8.0'))
Notice: /Stage[main]/Plone/Exec[/vagrant/buildout/bin/buildout]: Dependency Exec[/home/vagrant/py27/bin/python bootstrap.py] has failures: true
Notice: Finished catalog run in 9.66 seconds


Stderr from the command:

stdin: is not a tty
Error: /home/vagrant/py27/bin/python bootstrap.py returned 1 instead of one of [0]
Error: /Stage[main]/Plone/Exec[/home/vagrant/py27/bin/python bootstrap.py]/returns: change from notrun to 0 failed: /home/vagrant/py27/bin/python bootstrap.py returned 1 instead of one of [0]
Warning: /Stage[main]/Plone/Exec[/vagrant/buildout/bin/buildout]: Skipping because of failed dependencies

```

I can avoid this problem by:

- Removing the created virtualenv;
- Editing the plone.pp manifest adding [`--no-setuptools`](https://github.com/plone/training/blob/master/plone_training_config/manifests/plone.pp#L60) when creating the virtualenv.

Since the `--no-setuptools` argument is from virtualenv 1.9 and in Ubuntu 14 (used in Vagrant) [version is 1.11](http://packages.ubuntu.com/trusty/python/python-virtualenv), I think it's a nice solution.

I didn't test upgrading the [bootstrap.py](https://bootstrap.pypa.io/bootstrap-buildout.py) used in https://github.com/collective/training_buildout.git but I think it should be upgraded as well: we should pin the setuptools version when calling bootstrap.py to avoid this problem in the future.

**Comment by do3cc** [comment]
Hi,

did you try the plone5 branch? There we avoid vagrant alltogether, iirc

**Comment by idgserpro** [comment]
It works, but I need the 4.3.x branch. Since the plone5 branch [asks for setuptools 12](https://github.com/plone/training/blob/plone5/plone_training_config/manifests/plone.pp#L113) it doesn't conflict with zc.buildout 8.0 requirement.

Are you planning to completely avoid Vagrant in plone5 branch, or just going to be an "advanced" topic?

**Comment by do3cc** [comment]
I remembered it incorrectly. We had no windows laptops in our training.

**Comment by do3cc** [comment]
I've updated the repo to add your proposed fix. Can you try it again?

**Comment by idgserpro** [comment]
I made a mistake, I should have been clearer in my bug report.

Using the `--no-setuptools` option doesn't install pip.

I was using the [zip file in instructions](https://plone-training.readthedocs.org/en/latest/plone_training_config/instructions.html) and since it's manifests/plone.pp doesn't use pip, the `--no-setuptools` fix makes sense.

...but in the [repo master](https://github.com/plone/training/blob/master/plone_training_config/manifests/plone.pp#L112) you do use pip to upgrade setuptools, so just [adding --no-setuptools in your commit](https://github.com/plone/training/commit/cce9b4c1d33d769604b0a86b0df5f34c2b340610) breaks the provisioning again. pip usage was added in commit https://github.com/plone/training/blob/fa3c8db46954018512d3008220db9b582cc68bf5/plone_training_config/manifests/plone.pp.

Running `vagrant up` gives a new error:

```
ContextualVersionConflict: (setuptools 6.1 (/home/vagrant/buildout-cache/eggs/setuptools-6.1-py2.7.egg), Requirement.parse('setuptools>=8.0'), set(['zc.buildout']))
```

The correct thing here is:
- Change 6.1 to a higher setuptools version (I suggest to use the same in [plone5 branch](https://github.com/plone/training/blob/e6ef8029c4a5aa09653cf61039cd9d3f5c3eff93/plone_training_config/manifests/plone.pp#L113), **12.2**);
- Update the zip file used in https://plone-training.readthedocs.org/en/latest/plone_training_config/instructions.html.

Sorry about the hassle. I think you may `git commit --amend` to remove the `--no-setuptools` and just change the version 6.1 to 12.2.

PS: There [is a new Unified Installer for 4.3.4](https://launchpad.net/plone/4.3/4.3.4/+download/Plone-4.3.4-r1-UnifiedInstaller.tgz) as well.

**Comment by idgserpro** [comment]
@do3cc we can't change the code ourselves by pull requests since we can't sign the contributor's agreement. Can you [check the last comment](https://github.com/plone/training/issues/61#issuecomment-90664199)? Thanks in advance!

**Comment by do3cc** [comment]
@idgserpro Sorry, this got lost, I take care of it.

**Comment by do3cc** [comment]
btw, since there is no email, who are you? Are there really plone devs in BH? I pass by there regulary

**Comment by idgserpro** [comment]
This is a corporate account for Serpro - Serviço Federal de Processamento de Dados, an IT Brazilian Government company. All Zope/Python/Plone related activities in github are handled using this account. We're already contributing to some packages following an internal norm that guides how the contributions should be done (but not Plone core yet).

Yes, there are some Plone devs in BH. We'll try to get in touch by other accounts, but we can't guarantee to pass by München regularly. :)

BTW, this issue can be closed, the fix worked!

**Comment by do3cc** [comment]
Cool. Lets see. In january we will pass by on our trip to Montes Claros.
Regarding the Contributor Agreement, I think we can ignore this: 
https://github.com/plone/training/issues/62

**Comment by idgserpro** [comment]
Don't forget to change https://plone-training.readthedocs.org/en/latest/about.html#license to reflect this formal change to avoid confusion.

So, will the License be only a line long?

```
The Mastering Plone Training is licensed under a Creative Commons Attribution 4.0 International License.
```
