### ISSUE TITLE
Switch to 6.demo.plone.org from plonedemo.kitconcept.com

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#618]
Both the main Plone Documentation, which imports plone.restapi, and Plone Training were reporting broken links due to an expired secure certificate. @sneridagh fixed the certificate for now. However per a brief discussion in Discord, he recommended switching to the new 6.demo.plone.org site instead.

This brings up another issue, specifically that this site requires a basic authentication token to query the API, whereas plonedemo.kitconcept.com does not. Thus the examples in the training will fail. As such, I'll adjust the example to use a fake auth token.

**Comment by stevepiercy** [comment]
This issue blocks https://github.com/plone/training/issues/613

**Comment by ksuess** [comment]
I think you want a Plone website like 6.demo.plone.org, not documentation https://6.dev-docs.plone.org/

**Comment by stevepiercy** [comment]
ah, crap. fixing.
