### ISSUE TITLE
Direct people to more current channels for Contributor Agreement

### ISSUE THREAD

**Issue by fulv** [plone/training#63]
https://github.com/plone/training/blob/master/about.rst#license

Should we stop directing people to http://sourceforge.net/p/plone/mailman/plone-docs/, or plone-docs%40lists.sourceforge.net?

We could use community.plone.org, or github issues.

**Comment by gforcada** [comment]
I think the canonical place right now is https://plone.org/foundation/contributors-agreement

**Comment by fulv** [comment]
That canonical place is already cited in the License section, so I think we're good.  If the documentation team wants to handle inquiries about the CA via emails to the list, I guess that's their choice.
