### ISSUE TITLE
Copy and code snippets without extra line breaks

### ISSUE THREAD

**Issue by ksuess** [plone/training#666]
If code snippets are copied via selecting text and then pasted in editor, extra line breaks are inserted.

Example:
https://training.plone.org/5/mastering-plone/behaviors_2.html

**Comment by stevepiercy** [comment]
That's what the copy-paste code button solves. Perhaps we should make it a little more obvious? I mean, the code can be copied by clicking a single button versus click, drag, copy, should we spend time fixing this?

**Comment by ksuess** [comment]
it's been dealt with
