### ISSUE TITLE
Use sphinx-design to improve home page layout

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#671]
Now that the Hugo site is history, we should improve the appearance of the Training home page using [`sphinx-design`](https://sphinx-design.readthedocs.io/en/latest/) to emphasize the current and most important trainings.

**Comment by Ajeett01** [comment]
Hey , I wanted to contribute in this , I have read the 'Contributing to Plone Training' and signed the agreement , can you please explain the issue to me.
Thanks

**Comment by stevepiercy** [comment]
@Ajeett01 actually this issue is obsolete, since we archived trainings from 2022 and older. Closing.

**Comment by Ajeett01** [comment]
> @Ajeett01 actually this issue is obsolete, since we archived trainings from 2022 and older. Closing.

Ok , can you please tell any issue I can work on.

**Comment by stevepiercy** [comment]
No. That's your job. See Item 1 in https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues
