### ISSUE TITLE
Issue on page /voltohandson/footer.html

### ISSUE THREAD

**Issue by flipmcf** [plone/training#681]
Should we be throwing css into custom.overrides?  Would it be better practice to create a .less file inside our Footer directory and import it into footer.jsx

It might lead to bad habits... but maybe there was a good reason to use the overrides.

**Comment by tiberiuichim** [comment]
I think it's fine to have CSS in custom.overrides. There are a few (minor) differences in how the (generated) CSS loaded from components gets bundled into the CSS bundles, but the main one is that the css from .overrides will be closer to the "original" intended destination, the main CSS theme.

Having said that, I wouldn't worry too much about this issue. Just pick one style and be consistent with it.
