### ISSUE TITLE
Plone Deployment macOS tips

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#687]
zcsh on macOS 10.15 requires that for nvm commands, its options with glob characters `*` be quoted.

https://training.plone.org/plone-deployment/setup.html#node-and-node-tools

```
nvm install lts/*
nvm alias default lts/*
```

Should be:

```
nvm install 'lts/*'
nvm alias default 'lts/*'
```

**Comment by loechel** [comment]
even better would be to use -nvmrc in this context. But that should go into the cookiecutter template

**Comment by stevepiercy** [comment]
I like that idea. Can you capture that in the cookiecutter's issue tracker?

**Comment by stevepiercy** [comment]
Ooops, nm, I see you are way ahead of me https://github.com/collective/cookiecutter-plone-starter/issues/33 😁
