### ISSUE TITLE
Issue on page /mastering-plone/what_is_plone.html

### ISSUE THREAD

**Issue by MAX-786** [plone/training#695]
As mentioned in [Mastering Plone 6 at Ploneconf 2021. Part 1 of 2](https://www.youtube.com/watch?v=Jzuw3uWtzzI&t=1220s), on this page [Object publishing](https://training.plone.org/mastering-plone/what_is_plone.html#object-publishing) it should be mentioned that `Object publishing` is used by Plone 6 classic and Plone 6 uses `REST API`.

**Comment by ksuess** [comment]
Fixed by https://github.com/plone/training/pull/909
