### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by macagua** [plone/training#7]
Hi @pbauer 

Following the same way using docs.plone.org iniciative I created:
- A Transifex project called "mastering-plone-training" into Plone organization. https://www.transifex.com/projects/p/mastering-plone-training/
- Spanish translations and using as a resource in my Plone training. https://www.transifex.com/projects/p/mastering-plone-training/language/es/

Also I added support for Sphinx's translations using http://sphinx-doc.org/intl.html the same mechanism used to do the translations into docs.plone.org iniciative.

Well I would I like to merge this improvements, then...

Do you have any problems with this change?

**Comment by ramiroluz** [comment]
It is done? Should this issue be closed?

**Comment by stevepiercy** [comment]
We decided to remove translations because we update training docs every year, but no one updates the translations. Google Translate is sufficient, if not hilarious from time to time.
