### ISSUE TITLE
Broken links on master

### ISSUE THREAD

**Issue by svx** [plone/training#70]
running link check on the master branch gives me the following broken urls:
- broken    https://github.com/plone/training/pull/ - HTTP Error 404: Not Found
- broken      http://2013.pythonbrasil.org.br/program/training/mastering-plone - <urlopen error [Errno 111] Connection refused>
- broken    http://docs.plone.org/develop/addons/five-grok/index.html - HTTP Error 404: Not Found
- broken    http://docs.plone.org/develop/addons/five-grok/index.html - HTTP Error 404: Not Found
- broken    http://aptana.com/products/studio3/ - HTTP Error 404: Not Found

To make that sure, I also tested them from hand, well same result :)

**Comment by pbauer** [comment]
@svx: thanks. I will fix them.

**Comment by stevepiercy** [comment]
I fixed the crap out of hundreds of dead links. There are no more dead links. Closing.
