### ISSUE TITLE
mastering-plone-5-development.readthedocs.io

### ISSUE THREAD

**Issue by ksuess** [plone/training#700]
https://mastering-plone-5-development.readthedocs.io
Still indexed.
Any reason to keep?
If not, this should be eliminated. It's misleading to outdated content.

Example:
Search for "Plone registry"

**Comment by stevepiercy** [comment]
If it's operated by Plone, then it should go away. Who maintains it?

**Comment by ksuess** [comment]
> If it's operated by Plone, then it should go away. Who maintains it?

I guess @pbauer is maintainer.

**Comment by stevepiercy** [comment]
The source is https://github.com/bfreitas05/training.

@bfreitas05 would you please take down this obsolete training? It interferes with SEO for current Master Plone 5 Training. Please let us know. Thank you!

**Comment by stevepiercy** [comment]
I filed a support request on RTD: https://readthedocs.org/support/

---

Hello,

https://mastering-plone-5-development.readthedocs.io/en/latest/ is an outdated version of Mastering Plone 5 Development. It appears in search engine results, which takes away from the authoritative archived version at https://2023.training.plone.org/mastering-plone-5/index.html#mastering-plone5-label.

I have tried to reach out the user @bfreitas05 in https://github.com/plone/training/issues/700 to remove the site, but have received no response.

Would you please take down that site and project? Thank you!

--steve

**Comment by stevepiercy** [comment]
RTD was super quick. Closing as complete.
