### ISSUE TITLE
Mention of omelette directory in pages 12 and 14 of Mastering Plone 6 Development

### ISSUE THREAD

**Issue by curiousyuvi** [plone/training#711]
In the pages [Mastering Plone 6 Development > 12. Customizing Volto Components](https://training.plone.org/mastering-plone/volto_overrides.html#customizing-volto-components) and [Mastering Plone 6 Development > 14. Theming in Volto](https://training.plone.org/mastering-plone/volto_theming.html#theming-in-volto), there are multiple mentions of `omelette` directory that holds the original code for Volto which can be shadowed by files in `src/customizations` and `theme` directory.

This is not the case now, now we don't have code in `omelette` directory but rather the original code is present in `src` and `theme` directories itself.

**Comment by curiousyuvi** [comment]
Can someone validate this issue so that I can go ahead and create a PR for it, thank you.

**Comment by ksuess** [comment]
The Volto repo can be checked out and set up as Node app for development / making changes on Volto itself.
This is not what you want to set up a website. Please follow chapter 7 or 8 to set up a site.

**Comment by ksuess** [comment]
BTW for GSOC it is not necessary to collect merged PRs. Please read the instructions on https://community.plone.org/t/recommendations-for-gsoc-aspirants/16301.

**Comment by curiousyuvi** [comment]
> BTW for GSOC it is not necessary to collect merged PRs. Please read the instructions on https://community.plone.org/t/recommendations-for-gsoc-aspirants/16301.

😅 Well I'm not contributing just for the sake of GSoC.

**Comment by ksuess** [comment]
> > BTW for GSOC it is not necessary to collect merged PRs. Please read the instructions on https://community.plone.org/t/recommendations-for-gsoc-aspirants/16301.
> 
> 😅 Well I'm not contributing just for the sake of GSoC.

My appologies. Enjoy the training. Feel free to ask questions to Plone, Volto, whatever. We are curious to get feedback of your experience with Plone…
