### ISSUE TITLE
Missing Command during setting up volto

### ISSUE THREAD

**Issue by SaiRev0** [plone/training#714]
There is a **missing Command** in the volto setup training documentation

![image](https://user-images.githubusercontent.com/96655163/221571523-d27a0859-36b3-444a-a857-c775b27b70a7.png)

In the first part after the `cd my-volto-app` command, there should be a `yarn install` command before the `yarn start` command.
This will be a bit confusing for the new people who are not experienced enough.

So I guess it will be just better to add that command

**Comment by wesleybl** [comment]
@SaiRev0 when you run `yo @plone/volto`, it already runs yarn install.
