### ISSUE TITLE
Using a package name that starts with `volto` causes `plone/generator-volto` to fail

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#716]
@SaiRev0 it looks like this error happens when the package name starts with `volto`. I also saw this error:

```
/tmp/voltonew$ yarn start
Internal Error: voltonew@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at OR.getCandidates (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:435:5209)
    at Bd.getCandidates (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:391:1281)
    at /tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:439:7764
    at Tg (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:390:11154)
    at ce (/tmp/voltonew/.yarn/releases/yarn-3.2.3.cjs:439:7744)
```

Really in this situation, when running `yarn install`, it starts to work.

Until the issue is fixed we need to warn users on https://training.plone.org/volto/bootstrap.html with the following:

"Do not name your project starting with `volto`, as this will cause `plone/generator-volto` to fail."

_Originally posted by @wesleybl in https://github.com/plone/training/issues/715#issuecomment-1448126874_

**Comment by SaiRev0** [comment]
It's nice we found out a bug, we need to fix this issue. What according to you I causing this error??

I will also try to find the cause of the error

**Comment by SaiRev0** [comment]
@stevepiercy For the time being we should add a note as you said. So I am making a pr for adding that note

![image](https://user-images.githubusercontent.com/96655163/222145640-633a51ff-f66f-4388-839b-d4a8b1ebb6a4.png)

We should add that note between these 2 lines.
Will that be good?

**Comment by stevepiercy** [comment]
@SaiRev0 please read https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors applies to any text as image.

I absolutely refuse to respond to any text as image for those and other reasons. Instead submit a text-only suggestion, or better yet, a PR with your proposed change. Thank you!
