### ISSUE TITLE
Backend Installation issue -not able to build

### ISSUE THREAD

**Issue by Tishasoumya-02** [plone/training#717]
I tried  to build the backend as given in training documentation but it is failing to recognize venv, so I tried 
to first create a virtual env and then run this command then also no luck.

It would be great if someone here could help me with this. I am sorry if I am bothering with these silly questions :no_mouth:
![image](https://user-images.githubusercontent.com/66815801/222770605-4ddfb98b-caa9-4cb1-8c05-87d7f5f87c7a.png)

**Comment by wesleybl** [comment]
It looks like the create virtualenv command in training_buildout is wrong:

https://github.com/collective/training_buildout/blob/d4c780da1013da285f21cf01d39b51bb5f8a5932/Makefile#L31

This command should be `python3` not `python`

**Comment by ksuess** [comment]
I recommend to work on a Linux machine or Mac.
Despite I do not have experience with Windows and especially not with development on Windows, I think the recommendation to set up Windows Subsystem for Linux (WSL) sounds quite convincing. It seems to set up a Linux where you can install Python, e.a..

See the following intructions on how to set up WSL:
https://learn.microsoft.com/en-us/windows/python/web-frameworks
It even speaks about venv!

**Comment by Tishasoumya-02** [comment]
Thank you for your guidance . Now the server is working and I installed npm package for volto but I am not able to login as admin the alert keeps on recurring on the web browser. Btw I am running these on Ubuntu.
![image](https://user-images.githubusercontent.com/66815801/222904549-36cd458b-8bd4-4497-84c1-e2ba31817d79.png)
