### ISSUE TITLE
Unnecessary anchor tag in Plone 6 chapter 22 code block

### ISSUE THREAD

**Issue by Azzam1503** [plone/training#718]
On the page [Mastering Plone 6 development > 22. Volto View Component: A Default View for a "Talk"](https://training.plone.org/mastering-plone/volto_talkview.html) there is an unnecessary anchor tag ``<a href={`mailto:${content.email}`}>`` causing error in the code in the block where speaker email is added. The issue is only in this code block.

![Screenshot from 2023-03-01 09-51-25](https://user-images.githubusercontent.com/113233352/222782513-316a4e7a-adf1-450d-91d0-8e8bbdc4fac4.png)

**Comment by Azzam1503** [comment]
#719

**Comment by ksuess** [comment]
Please help me to understand. Why do you think this node is unnecessary? What kind of error has been arisen?

**Comment by Azzam1503** [comment]
First, this anchor tag is not closed so it is causing an error in the code 
```javascript
<a href={`mailto:${content.email}`}>
{content.email && (
          <p>
            Email: <a href={`mailto:${content.email}`}>{content.email}</a>
          </p>
        )}
```
 Second, It is the extra anchor tag the main anchor tag is in the paragraph and it is only present in this block of code not in the next blocks of code.

**Comment by Azzam1503** [comment]
Thanx @ksuess for merging my pull request. Although small but it is my first open-source contribution.

**Comment by ksuess** [comment]
Fixed by @Azzam1503  in  https://github.com/plone/training/pull/719

**Comment by ksuess** [comment]
> Thanx @ksuess for merging my pull request. Although small but it is my first open-source contribution.

Every great journey begins with a small step.
