### ISSUE TITLE
[Training "React"] Updation needed in the folder structure of the React Training (bootstrap.html#bootstrapping-a-project)

### ISSUE THREAD

**Issue by rakshith6404** [plone/training#727]
The Folder structure which is given is to be updated in the react part of the training,the [Bootstrapping](https://training.plone.org/5/react/bootstrap.html#bootstrapping-a-project) part of the React training 

Folder structure given in the [Training](https://training.plone.org/5/react/bootstrap.html#bootstrapping-a-project) 

Current Structure when you make a React-app using ```npx create-react-app my-app```:

![Screenshot from 2023-03-07 14-47-54](https://user-images.githubusercontent.com/92712034/223381374-a4f2fa95-69f7-4bc6-bdf3-699be6360353.png)

**Comment by stevepiercy** [comment]
Please submit a PR with a correction using the `tree` command. Thank you!

**Comment by rakshith6404** [comment]
Closing this issue and marking this as done
