### ISSUE TITLE
Installtion process-python command cannot be found, can be rectified.

### ISSUE THREAD

**Issue by Tishasoumya-02** [plone/training#732]
In the installation process of plone for training an error occurs -python command cannot be found so we can either specifically mention in the docs to edit the makefile and change `python -m venv venv ` to `python3 -m venv venv` or directly make changes in the repository from where the code is getting cloned on to our system.

**Comment by wesleybl** [comment]
@Tishasoumya-02 I think the correct thing to do here is to change in the repository:

https://github.com/collective/training_buildout/blob/d4c780da1013da285f21cf01d39b51bb5f8a5932/Makefile#L31

**Comment by stevepiercy** [comment]
I agree with @wesleybl. @Tishasoumya-02 would you be so kind as to create a new issue in that repository, and reference this issue? And better yet, please create a PR to make that change? Thank you!

**Comment by Tishasoumya-02** [comment]
Sure @wesleybl @stevepiercy .
