### ISSUE TITLE
Plone Training Documentation still as 2022

### ISSUE THREAD

**Issue by rakshith6404** [plone/training#738]
I was going the docs for the training and saw that Plone Training documentation still is on 2022 , 

If this issue is alreaady fixed pls do close it @stevepiercy 
![Screenshot from 2023-03-11 11-36-40](https://user-images.githubusercontent.com/92712034/224468253-dfa5a234-ce95-4187-87bf-eaa90cc6475d.png)

**Comment by stevepiercy** [comment]
Which URL?

How did you find the URL?

I suspect your went to an archived URL at `/5/`.

See https://github.com/plone/training/issues/672

**Comment by rakshith6404** [comment]
> I suspect your went to an archived URL at `/5/`.

I guess to the URL with the ```/5/``` , i visited this [Link](https://training.plone.org/5/index.html)

If ```/5/``` is the older version and with the 202 version why isnt it remove from as the domain?

Are the curate things which is mentioned above are the things to be done?

**Comment by stevepiercy** [comment]
How did you find the URL `https://training.plone.org/5/index.html`? Search engine? Link on another page? Sacrificing a small furry animal to Cthulu?

> Are the curate things which is mentioned above are the things to be done?

Yes.

**Comment by rakshith6404** [comment]
> Search engine? Link on another page?

I was using this URL 2 month ago when i was going through the training documentation.And also recently i searched Google for the latest training for plone ```Plone training``` and the 2 link which redirects you to this link.

![Screenshot from 2023-03-11 14-52-20](https://user-images.githubusercontent.com/92712034/224476333-8c2844e5-7b3d-4c98-97cd-65c1cc0211c9.png)

![Screenshot from 2023-03-11 14-52-36](https://user-images.githubusercontent.com/92712034/224476337-20ab9b54-3c95-4a25-8b77-4c3397a3952c.png)


@stevepiercy should i close this issue ??

**Comment by stevepiercy** [comment]
Yes, thank you. That confirms our suspicions. We are finding lots of links throughout our repos to the old training. Closing.

**Comment by rakshith6404** [comment]
> Yes, thank you. That confirms our suspicions. We are finding lots of links throughout our repos to the old training. Closing.

@stevepiercy how could this be fixed?? changing the whole 2022 documentation to 2023 might work??

**Comment by stevepiercy** [comment]
No, please see the plan in https://github.com/plone/training/issues/672

The only thing for people who are neither trainers nor sysadmins to do is find and replace any links in any repo that point to `https://training.plone.org/5/*` and change them to `https://training.plone.org/*`.
