### ISSUE TITLE
Replace links to `https://training.plone.org/5/*` with `https://training.plone.org/*` across Plone org

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#740]
Find and replace any link in any repo in the Plone organization that points to `https://training.plone.org/5/*` and change it either to `https://training.plone.org/*` if they shall be retained, or to `https://2022.training.plone.org/*` if they shall be archived.

To find the source files, use the search https://github.com/search?o=desc&q=org%3Aplone+%22https%3A%2F%2Ftraining.plone.org%2F5%2F%22&s=indexed&type=Code (For an exact match of the URL, see [Enabling and disabling the new code search and code view (beta)](https://docs.github.com/en/search-github/github-code-search/about-github-code-search#enabling-and-disabling-the-new-code-search-and-code-view-beta))

The highest priority would be the repos that have been indexed within the last year.

See the list of trainings: https://docs.google.com/spreadsheets/d/1Wmg03uXD3fIRYz33xPFnzaFbLYdxjhKq10NAKDswFxg/edit#gid=0

## Update default Volto training

This is an exception to the general rules for archival and retention.

- Old default: [Volto](https://training.plone.org/volto/index.html) `https://training.plone.org/volto/index.html`
- New default: [Volto Hands-On](https://training.plone.org/voltohandson/index.html) `https://training.plone.org/voltohandson/index.html`

## To be archived to `https://2022.training.plone.org/*`

Training Name | Training URL
-- | --
Angular SDK for Plone | https://training.plone.org/angular/index.html
Automating Plone Deployment | https://training.plone.org/deployment/index.html
Build your own webframework from scratch | https://training.plone.org/advanced-python/index.html
Deploying and Operating Plone on WSGI | https://training.plone.org/wsgi/index.html
GatsbyJS | https://training.plone.org/gatsby/index.html
JavaScript For Plone Developers (up to Plone 5) | https://training.plone.org/javascript/index.html
Migrating Content with Transmogrifier | https://training.plone.org/transmogrifier/index.html
Plone 5 Theming | https://training.plone.org/theming_plone_5/index.html
Plone Deployments With Amazon OpsWorks | https://training.plone.org/deployment/opsworks/index.html
Plone Training Solr | https://training.plone.org/solr/index.html
React | https://training.plone.org/react/index.html
Through-The-Web Plone Customization | https://training.plone.org/ttw/index.html

## To be retained at `https://training.plone.org/*`

Training Name | Training URL
-- | --
Effective Volto | https://training.plone.org/effective-volto/index.html
Mastering Plone 5 Development | https://training.plone.org/mastering-plone-5/index.html
Mastering Plone 6 Development | https://training.plone.org/mastering-plone/index.html
Migration best practices | https://training.plone.org/migrations/index.html
Patternslib | https://patternslib.github.io/patternslib-training/
Plone 6 Classic UI Theming | https://training.plone.org/theming/index.html
Plone Deployment | https://training.plone.org/plone-deployment/index.html
Plone Workflow | https://training.plone.org/workflow/index.html
Testing Plone | https://training.plone.org/testing/index.html
Volto Add-ons Development | https://training.plone.org/voltoaddons/index.html
Volto Hands-On | https://training.plone.org/voltohandson/index.html

**Comment by ksuess** [comment]
Links to trainings that will be archived soon accorging https://github.com/plone/training/issues/672 needs to be updated to 2022.training.plone.org/*. Other links to training.plone.org/*.
I'll take this issue.

**Comment by yahya-cloud** [comment]
can i also update few links ?

**Comment by stevepiercy** [comment]
> Links to trainings that will be archived soon according #672 needs to be updated to `2022.training.plone.org/*`. The other links to `training.plone.org/*`.

Thanks. You are correct. I updated the original issue description for clarity.

> can i also update few links ?

You sure can! :grin: Please check with @ksuess to avoid duplicating efforts.

**Comment by stevepiercy** [comment]
There is one exception to the above, and I just updated the plan to reflect that. After the Volto team meeting earlier today, I followed up to ask what should be the new default Volto training, now that the current default will be archived. The new default will be Volto Hands-On.

## Update default Volto training

This is an exception to the general rules for archival and retention.

- Old default: [Volto](https://training.plone.org/volto/index.html)
- New default: [Volto Hands-On](https://training.plone.org/voltohandson/index.html)

**Comment by stevepiercy** [comment]
I've created 5 PRs to update the links. That's about all that is really needed. There are a bunch for archives, but that's not necessary.

**Comment by stevepiercy** [comment]
All PRs are merged. Closing. Yee-haw!
