### ISSUE TITLE
Mistake on Plone 6  38. Relation Page

### ISSUE THREAD

**Issue by Azzam1503** [plone/training#743]
On the [page Master Plone 6 > 38. Realtions](https://training.plone.org/5/mastering-plone/relations.html#configure-the-relateditemsfieldwidget) dropdown is misspelled as dropwdown and (and) is used twice on the same line.

![Screenshot from 2023-03-15 02-38-33](https://user-images.githubusercontent.com/113233352/225138007-deea0d22-7830-4a6d-8df0-14de8e45f5f9.png)

**Comment by stevepiercy** [comment]
Closed by #744
