### ISSUE TITLE
Mistake on Plone 6 on 40. Complex Behaviors

### ISSUE THREAD

**Issue by Azzam1503** [plone/training#745]
On the page [Mastering Plone 6 > 40. Complex Behaviors](https://training.plone.org/5/mastering-plone/behaviors_2.html) Therefore is misspelled as Therfore.
![Screenshot from 2023-03-15 14-49-17](https://user-images.githubusercontent.com/113233352/225265432-2e0bde66-b741-4cfd-a4de-81be22a1473e.png)

**Comment by stevepiercy** [comment]
Closed by #746
