### ISSUE TITLE
Mistakes on Plone 6 training > 42. Volto Actions and Component State

### ISSUE THREAD

**Issue by Azzam1503** [plone/training#747]
On page [Plone 6 > 42. Volto Actions and Component State](https://training.plone.org/5/mastering-plone/volto_actions.html), there are some typos:
Successfull should be successful
endpint should be endpoint
definitly should be definitely
![Screenshot from 2023-03-15 18-26-26](https://user-images.githubusercontent.com/113233352/225315465-868f2c5b-fdf9-4362-b8cd-49269d97200d.png)
![Screenshot from 2023-03-15 18-26-51](https://user-images.githubusercontent.com/113233352/225315509-c8e81f11-bd95-4a45-a0b6-a4d8e846a6eb.png)
![Screenshot from 2023-03-15 18-27-09](https://user-images.githubusercontent.com/113233352/225315528-b5f62ea1-6d48-4a42-8cc4-15165b0a26ca.png)

**Comment by stevepiercy** [comment]
@Azzam1503 GitHub did not auto-close this. I think you need to put the GitHub comment as the first comment, which [GitHub calls "description"](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Subsequent comments have no effect. TIL.
