### ISSUE TITLE
Master Plone 6 welcome page screenshot is of 5.2

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#749]
On https://training.plone.org/mastering-plone/features.html, the screenshot https://training.plone.org/_images/frontpage_plone.png looks like it is from Plone 5.2.

**Comment by shubhambhar007** [comment]
@stevepiercy can you please tell me if this image is to be removed from the page or some other image be added in place of this ? Thanks

**Comment by stevepiercy** [comment]
@shubhambhar007 replaced.

Also please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by ksuess** [comment]
Sorry, @stevepiercy , that I missed this issue. 
The screenshot has been updated in the meantime. So I close this issue. Feel free to reopen, if I missed a thing.
