### ISSUE TITLE
Add Traefik to Glossary and to Plone Deployment training

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#759]
There are two good resources that should be mentioned.

- General information for the Glossary: https://traefik.io/

- Implementation detail for the [Plone Deployment](https://training.plone.org/plone-deployment/index.html) training: https://dockerswarm.rocks/traefik/

Refs: https://github.com/collective/cookiecutter-plone-starter/pull/75#issuecomment-1520900771

**Comment by Ajeett01** [comment]
Is this issue open

**Comment by stevepiercy** [comment]
@Ajeett01 see item 4 in https://6.docs.plone.org/contributing/first-time.html#things-not-to-do and please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).
