### ISSUE TITLE
Breadcrumbs of search results are missing

### ISSUE THREAD

**Issue by ksuess** [plone/training#776]
…after update of theme.

![grafik](https://github.com/plone/training/assets/1144737/e5925801-818e-42cc-ab19-2d2f064224aa)

**Comment by stevepiercy** [comment]
Thanks @ksuess. We are working on Nuclia search for GSoC, which will replace Sphinx search results. @justdaksh @ebrehault would you like to include this in the Nuclia search results as a feature request? Let's discuss during our next meeting.
