### ISSUE TITLE
Placeful workflows are not yet configurable in Volto ?

### ISSUE THREAD

**Issue by frchalaoux** [plone/training#794]
In https://training.plone.org/mastering-plone/features.html#placeful-workflows it is specified :

"Placeful workflows are not yet configurable in Volto. Workflow settings that are configured in Plone backend are applied though."

For me it seems to work in Volto interface http://localhost:3000/controlpanel/addons to Add in Plone the capability to change workflow chains for types in every object. Includes a dependency on core Plone types.

Maybe the training could be corrected if you validate this add-on installation ?

If it is working only in backend I can't find the way to do it and will appreciate to have a link to discover it !

François-Régis

**Comment by ksuess** [comment]
Sorry for this late answer.

Workflows are in most cases configured per type.
This configuration is done in a policy add-on of your project (/backend/src/abcd/sandboxpolicy/profiles/default/workflow/) and can be tried out through the web:

![content_settings_workflow](https://github.com/user-attachments/assets/35261f6a-e752-4b92-9881-3a1f897820b4)


In some cases a page, with its subpages, needs a special workflow. For example the website has an intranet part which should be available only for authenticated users or special group of users. Then the placeful workflow is the way to go. 
After activating the (per default always available) add-on "Workflow Policy Support (CMFPlacefulWorkflow)" you can go to your page "intranet" and apply a workflow of your choice to this page and its subpages.

![placeful_workflow](https://github.com/user-attachments/assets/0f701de7-48b1-41a5-9d80-3eec0cfb283a)

Both configurations can be done (just playing, not in a productive environment) in Plone Classic UI, but by now not in Volto. But of course the effects are applied though in Volto.
