### ISSUE TITLE
Typo in /mastering-plone/features.html

### ISSUE THREAD

**Issue by prathamjagga** [plone/training#811]
![image](https://github.com/plone/training/assets/30550632/193b55e2-e297-4ac8-81dc-eefdc60b9e4c)

Issue: "glimpse" is written as "glimps". Correct this typo, please.

**Comment by stevepiercy** [comment]
@prathamjagga you are welcome to submit a pull request with the correction. Thank you!

**Comment by prathamjagga** [comment]
hi @stevepiercy , there are actually a lot of typos and grammar errors in the training, I'll have a look at it once, and submit a PR.

**Comment by Vivek-04022001** [comment]
@stevepiercy  I hope you're doing good. I went ahead and sent a pull request for glossary changes. Is that cool, or should I have started with an issue? I spotted the "suggest an edit" option and fixed some stuff. Would love to hear what you think.

**Comment by stevepiercy** [comment]
@Vivek-04022001 that's great!

For future PRs, if you want to avoid the statement for every pull request, you can use the preferred option of signing the Plone Contributor Agreement, especially if you intend to become a regular contributor in Plone or any of its packages, including Volto. See [Granting permission to publish](https://training.plone.org/contributing/index.html#granting-permission-to-publish).

**Comment by stevepiercy** [comment]
Closing as fixed.
