### ISSUE TITLE
Issue on page /voltohandson/footer.html

### ISSUE THREAD

**Issue by Molochem** [plone/training#812]
Most of the Links provided in the Footer are broken since they are ripped straight from the Plone Homepage.
Makes it very frustrating to follow the Tutorial.
Can Provide a Pull if needed.

**Comment by stevepiercy** [comment]
@Molochem yes, please. Also please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). Thank you!

**Comment by Molochem** [comment]
hey @stevepiercy I just finished going over the Tutorial and fixing various Typos, Gramatical Errors and some Code Snippets.

I also signed the Plone Contributors Agreement and went over the Rules for first time Committers.

**Comment by jackahl** [comment]
fixed with #813
