### ISSUE TITLE
Typo issue in Content Types I 

### ISSUE THREAD

**Issue by jsrjhbaryan959** [plone/training#843]
There is a typo issue in Content Types I of the plone 6 training docs, the issue is in 10.4 Behaviours paragraph. Kindly find the attached screenshot, that describes the issue.
![Screenshot (86)](https://github.com/plone/training/assets/99543379/14d0b75c-80a0-4f38-8081-945db7cbae3e)

Kindly, assign me this issue, I would like to work upon this and get started with my first contribution in Plone Community.

**Comment by stevepiercy** [comment]
@jsrjhbaryan959 please read and follow [Contributing](https://training.plone.org/contributing/), [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), and [Contributing to Plone](https://6.docs.plone.org/contributing/index.html).
