### ISSUE TITLE
Update search options according to available trainings

### ISSUE THREAD

**Issue by ksuess** [plone/training#845]

**Comment by stevepiercy** [comment]
I've been working on Plone Sphinx Theme and released it, which will incorporate Nuclia Search in a future release. I'm afraid that this work will be superseded by that work in a couple of weeks. I've been posting in Community, Discord, team meetings, and issue trackers this plan.

**Comment by ksuess** [comment]
I am looking forward to your new beautiful theme with Nuclia search. It will be great to have all resources included in the search. I set it up locally and it looks very nice.

In the meantime the search filter options could be updated. By now the options do include trainings that are not anymore available on docs.plone.org. 
I am aware that this search will be replaced by a Nuclia search.

**Comment by stevepiercy** [comment]
Excellent. FYI, I plan to work remotely on integrating Nuclia search at Buschenschanksprint, in case you want to join in. We also need to take a snapshot of 2023 trainings and prepare for 2024.
