### ISSUE TITLE
Vale and VSCode

### ISSUE THREAD

**Issue by ksuess** [plone/training#857]
How do I enable VSCode to mark suggestions, warnings, etc inline in *.md file?

I tried both released and pre-released version of 'Vale VSCode' extension.

My settings:

![grafik](https://github.com/user-attachments/assets/fe6623ce-0b31-4c39-a1aa-45defb010d66)

I do not see the problems inline in a file, nor do I see any problems listed below.

**Comment by stevepiercy** [comment]
I don't see a value for the config or the path to vale cli. This is more of a support issue with VSCode. See https://github.com/chrischinchilla/vale-vscode

**Comment by ksuess** [comment]
brewed

**Comment by stevepiercy** [comment]
@ksuess see also https://github.com/plone/documentation/blob/6.0/.vscode/settings.json. I use PyCharm, so I can't verify it would work in Training.
