### ISSUE TITLE
Mastering Plone 5 should be removed from Training

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#869]
Now that [Plone 5.2 has reached end of life status](https://plone.org/download/release-schedule), I would like to remove Mastering Plone 5 from the current list of trainings. It can still be found in the archive at https://2023.training.plone.org/mastering-plone-5/index.html.

@ksuess @pbauer please let me know if there is any reason to keep it in the main trainings. Thank you!

**Comment by ksuess** [comment]
I am + 1 for archiving it. 
I was a little hesitant because this training handles all the tasks of the current training in Classic UI manner, instead of explaining it for Volto. But, yes, it is still available and indexed in search engines, even if archived. So +1 for archiving the training.

**Comment by yurj** [comment]
Is there a place that collects all the trainings? I'm a little confuse by trainings dates, there's 2022, 2023 and 2024. Shouldn't it by Plone version instead of year?

**Comment by stevepiercy** [comment]
@yurj we decided to use year to align with the annual PloneConf. Most trainings tend to be updated only once per year, if ever, and need to be archived from time to time. See also https://community.plone.org/t/plone-6-documentation-update-2023-04-13-curating-trainings-and-dark-mode-is-coming/17357#training-1.
