### ISSUE TITLE
Dont use diff in VLT training

### ISSUE THREAD

**Issue by jackahl** [plone/training#885]
At https://github.com/plone/training/blob/main/docs/customizing-volto-light-theme/installing-vlt.md#step-3-configure-volto-light-theme-as-the-theme-provider there is a git diff used to show what needs to got into volto.config.js. This

1. does not work very well with our docs renderer: https://training.plone.org/customizing-volto-light-theme/installing-vlt.html#step-3-configure-volto-light-theme-as-the-theme-provider
2. is not consistent with the other code snippets in the training

**Comment by stevepiercy** [comment]
@jackahl what would you suggest to improve the situation? We have lots of options. See https://6.docs.plone.org/contributing/documentation/myst-reference.html#code-block for a few options.

**Comment by stevepiercy** [comment]
For even more options, see https://myst-parser.readthedocs.io/en/latest/syntax/code_and_apis.html.

**Comment by jackahl** [comment]
@stevepiercy guess just the full new json structure in a code block. Would even be less lines and more clear for readers. As there is no proper syntax highlighting for those sorts off git diffs, I think we should try to avoid them when possible. I know there are cases, where showing a diff might be necessary.

**Comment by stevepiercy** [comment]
@jackahl OK, and if there are specific line numbers that you want to highlight to indicate that they were changed, we can use `emphasize-lines` instead of the diff. Here's a PR to review and comment on: https://github.com/plone/training/pull/887
