### ISSUE TITLE
Incorrect YouTube Embed URL in Volto Default Theme Documentation

### ISSUE THREAD

**Issue by Pulkitxm** [plone/training#897]
The [Volto default theme documentation](https://training.plone.org/mastering-plone/what_is_plone.html#:~:text=The%20Volto%20default%20theme%20is%20based%20on%20Semantic%20UI%20theme%20and%20is%20called%20Pastanaga.) contains an incorrect YouTube embed URL.

Current URL:
`https://www.youtube-nocookie.com/embed/wW9mTl1Tavc&t=133s&privacy_mode=1`

Correct URL:
`https://www.youtube-nocookie.com/embed/wW9mTl1Tavc?t=133s&privacy_mode=1`

**Comment by stevepiercy** [comment]
@Pulkitxm thanks for the report. Would you please create a PR to fix it? Thank you!

**Comment by Pulkitxm** [comment]
@stevepiercy Fixing it now, thanks!
