### ISSUE TITLE
Custom search (Unit 27) plone 5 compat

### ISSUE THREAD

**Issue by fulv** [plone/training#97]
Meta:  I'm going to create a "Plone 5" label, and start adding issues with that label, so we can keep track of what is still not ready on the plone5 branch.

This one is about the `custom_search.rst` page, on eea.facetednavigation, which is not compatible with plone 5 yet.

We should find out the eta for eea.facetednavigation to be made compatible.
And hide this unit from the training until it's meaningful.

**Comment by do3cc** [comment]
Last I heard eea is not yet supporting plone5, because they don't need compatibility. I have provided some patches to make it more compatible, but this is probably still a volunteer only effort

**Comment by stevepiercy** [comment]
Plone 5 is now supported for this. Closing.
